###Define interesting aircraft to be all types
$env:AIRCRAFT_TYPES=""
#$env:AIRCRAFT_TYPES="MILITARY"

$env:AIRCRAFT_TYPES_EXCL2=""
$env:AIRCRAFT_TYPES_CONFIRMED=""
$env:AIRCRAFT_TYPES_EXCL=""






#AIR TRACTOR
$env:AIRCRAFT_TYPES_EXCL2+=",AT3P" #AIR TRACTOR AT-301/401
$env:AIRCRAFT_TYPES_EXCL2+=",AT3T" #AIR TRACTOR AT-302/402
$env:AIRCRAFT_TYPES_EXCL2+=",AT5T" #AIR TRACTOR AT-504
$env:AIRCRAFT_TYPES_EXCL2+=",AT6T" #AIR TRACTOR AT-602
$env:AIRCRAFT_TYPES_EXCL2+=",AT8T" #AIR TRACTOR AT-802




#ATR
$env:AIRCRAFT_TYPES_EXCL2+=",AT43" #ATR-42-300
$env:AIRCRAFT_TYPES_EXCL2+=",AT45" #ATR-42-500
$env:AIRCRAFT_TYPES_EXCL2+=",AT46" #ATR-42-600
$env:AIRCRAFT_TYPES_EXCL2+=",AT75" #ATR-72-500
$env:AIRCRAFT_TYPES_EXCL2+=",AT72" #ATR-72-202
$env:AIRCRAFT_TYPES_EXCL2+=",AT73" #ATR-72-212
#$env:AIRCRAFT_TYPES_EXCL2+=",AT75"
$env:AIRCRAFT_TYPES_EXCL2+=",AT76" #ATR-72-600

#ALENIA
$env:AIRCRAFT_TYPES_EXCL2+=",G222" #ALENIA C-27A Spartan
$env:AIRCRAFT_TYPES_EXCL2+=",C27J" #ALENIA C-27J Spartan


#AERO Let
$env:AIRCRAFT_TYPES_EXCL2+=",L29" #AERO L-29 Delfin
$env:AIRCRAFT_TYPES_EXCL2+=",L39" #LET L-39 Albatros
$env:AIRCRAFT_TYPES_EXCL2+=",L159" #AERO L-159 Albatros 2
$env:AIRCRAFT_TYPES_EXCL2+=",L410" #LET L-410 Turbolet

#AERO
$env:AIRCRAFT_TYPES_EXCL2+=",AAT3" #AERO AT-3
$env:AIRCRAFT_TYPES_EXCL2+=",AAT4" #AERO AT-4

#AEROPRACT
$env:AIRCRAFT_TYPES_EXCL+=",AP22" #AEROPRACT A-22
$env:AIRCRAFT_TYPES_EXCL2+=",AP32" #AEROPRACT A-32

#AERONCA
$env:AIRCRAFT_TYPES_EXCL2+=",AR11" #AERONCA 11 Chief
$env:AIRCRAFT_TYPES_EXCL2+=",AR15" #AERONCA 15 Sedan

#AEROSPOOL
$env:AIRCRAFT_TYPES_EXCL2+=",WT9" #AEROSPOOL WT-9 Dynamic
$env:AIRCRAFT_TYPES_EXCL2+=",WT10" #AEROSPOOL WT-10 Advantic


#AERO Commander / NORTH AMERICAN / ROCKWELL  / THRUSH
#rockwell
$env:AIRCRAFT_TYPES_EXCL+=",VO10" #NORTH AMERICAN ROCKWELL Commander 100
$env:AIRCRAFT_TYPES_EXCL+=",M200" #NORTH AMERICAN ROCKWELL Commander 200
$env:AIRCRAFT_TYPES_EXCL+=",AC11" #NORTH AMERICAN ROCKWELL Commander 112/114
$env:AIRCRAFT_TYPES_EXCL+=",AC50" #NORTH AMERICAN ROCKWELL Commander 500
$env:AIRCRAFT_TYPES_EXCL+=",AC68" #AERO Commander 680
$env:AIRCRAFT_TYPES_EXCL+=",RC70" #ROCKWELL Commander 700/710
$env:AIRCRAFT_TYPES_EXCL+=",AC80" #NORTH AMERICAN ROCKWELL Turbo Commander 680
$env:AIRCRAFT_TYPES_EXCL+=",AC90" #NORTH AMERICAN ROCKWELL Turbo Commander 690/840
$env:AIRCRAFT_TYPES_EXCL+=",AC95" #NORTH AMERICAN ROCKWELL Jetprop Commander 1000
#Thrush
$env:AIRCRAFT_TYPES_EXCL+=",SS2P" #ROCKWELL Thrush Commander
$env:AIRCRAFT_TYPES_EXCL+=",SS2T" #TRUSH Turbo Thrush 500/550
$env:AIRCRAFT_TYPES_EXCL+=",A660" #THRUSH S-2R Turbo 660
#WW2
$env:AIRCRAFT_TYPES_CONFIRMED+=",P51" #NORTH AMERICAN P-51  Mustang
$env:AIRCRAFT_TYPES_EXCL2+=",T6" #NORTH AMERICAN T-6 Texan
$env:AIRCRAFT_TYPES_EXCL2+=",T28" #NORTH AMERICAN T-28
$env:AIRCRAFT_TYPES_EXCL+=",NAVI" #NORTH AMERICAN Navion
$env:AIRCRAFT_TYPES_EXCL2+=",YALE" #NORTH AMERICAN Yale
#Military Modern
$env:AIRCRAFT_TYPES_CONFIRMED+=",V10" #NORTH AMERICAN OV-10 Bronco
$env:AIRCRAFT_TYPES_CONFIRMED+=",B1" #Rockwell B-1B Lancer
#Jets
$env:AIRCRAFT_TYPES_EXCL+=",SBR1" #NORTH AMERICAN Sabre 40/50/60/65

#ALPI
$env:AIRCRAFT_TYPES_EXCL2+=",PNR2" #ALPI Pioneer 200
$env:AIRCRAFT_TYPES_EXCL2+=",PNR3" #ALPI Pioneer 330
$env:AIRCRAFT_TYPES_EXCL2+=",PNR4" #ALPI Pioneer 400

#AMERICAN
$env:AIRCRAFT_TYPES_EXCL+=",AA1" #AMERICAN AA-1
$env:AIRCRAFT_TYPES_EXCL+=",AA5" #AMERICAN AA-5 Tiger


#ANTONOV
$env:AIRCRAFT_TYPES_CONFIRMED+=",AN2" #ANTONOV An-2
$env:AIRCRAFT_TYPES_CONFIRMED+=",AN12" #ANTONOV An-12
$env:AIRCRAFT_TYPES_CONFIRMED+=",AN26" #ANTONOV An-26
$env:AIRCRAFT_TYPES_CONFIRMED+=",AN28" #ANTONOV An-28
$env:AIRCRAFT_TYPES_CONFIRMED+=",A124" #ANTONOV An-124 Ruslan

#ATEC
$env:AIRCRAFT_TYPES_EXCL2+=",ZEPH" #ATEC Zephyr
$env:AIRCRAFT_TYPES_EXCL2+=",FAET" #ATEC 321 Faeta

#AUSTER
$env:AIRCRAFT_TYPES_EXCL2+=",J1" #AUSTER J-1
$env:AIRCRAFT_TYPES_EXCL2+=",D4" #AUSTER D-4
$env:AIRCRAFT_TYPES_EXCL2+=",D5" #AUSTER D-5
$env:AIRCRAFT_TYPES_EXCL2+=",ACAR" #AUSTER J-5 Autocar
$env:AIRCRAFT_TYPES_EXCL2+=",AUS5" #AUSTER AOP5




#Airbus
$env:AIRCRAFT_TYPES_EXCL2+=",A306" #AIRBUS A-300-600
$env:AIRCRAFT_TYPES_EXCL2+=",A30B" #AIRBUS A-300-200
$env:AIRCRAFT_TYPES_CONFIRMED+=",A3ST" #AIRBUS A-300ST Beluga Super Transporter
$env:AIRCRAFT_TYPES_EXCL2+=",A310" #AIRBUS A-310
$env:AIRCRAFT_TYPES_EXCL2+=",A318" #AIRBUS A-318
$env:AIRCRAFT_TYPES_EXCL+=",A319" #AIRBUS A-319
$env:AIRCRAFT_TYPES_EXCL+=",A19N" #AIRBUS A-319neo
$env:AIRCRAFT_TYPES_EXCL+=",A320" #AIRBUS A-320
$env:AIRCRAFT_TYPES_EXCL+=",A20N" #AIRBUS A-320neo
$env:AIRCRAFT_TYPES_EXCL2+=",A321" #AIRBUS A-321
$env:AIRCRAFT_TYPES_EXCL2+=",A21N" #AIRBUS A-321neo
$env:AIRCRAFT_TYPES_EXCL2+=",A332" #AIRBUS A-330-200
$env:AIRCRAFT_TYPES_EXCL2+=",A333" #AIRBUS A-330-300
$env:AIRCRAFT_TYPES_CONFIRMED+=",A337" #AIRBUS A-330-700 Beluga XL
$env:AIRCRAFT_TYPES_EXCL2+=",A338" #AIRBUS A-330-800
$env:AIRCRAFT_TYPES_EXCL2+=",A339" #AIRBUS A-330-900
$env:AIRCRAFT_TYPES_EXCL2+=",A342" #AIRBUS A-340-200
$env:AIRCRAFT_TYPES_EXCL2+=",A343" #AIRBUS A-340-300
$env:AIRCRAFT_TYPES_EX+=",A345" #AIRBUS A-340-500
$env:AIRCRAFT_TYPES_EXCL2+=",A346" #AIRBUS A-340-600
$env:AIRCRAFT_TYPES_EXCL2+=",A359" #AIRBUS A-350-900
$env:AIRCRAFT_TYPES_EXCL2+=",A35K" #AIRBUS A-350-1000
$env:AIRCRAFT_TYPES_EXCL2+=",A388" #AIRBUS A-380-800
#Military
$env:AIRCRAFT_TYPES_CONFIRMED+=",A400"

#Bombarier, now Airbus 
$env:AIRCRAFT_TYPES_EXCL+=",BCS1,BCS3"

#BAE / Avro / BAC
$env:AIRCRAFT_TYPES_EXCL2+=",JPRO" #BAC P-84 Jet Provost
$env:AIRCRAFT_TYPES_EXCL2+=",RJ70" #AVRO RJ-70 Avroliner
$env:AIRCRAFT_TYPES_EXCL2+=",RJ85" #AVRO RJ-85 Avroliner
$env:AIRCRAFT_TYPES_EXCL2+=",RJ1H" #AVRO RJ-100 Avroliner
$env:AIRCRAFT_TYPES_EXCL2+=",B461" #BRITISH AEROSPACE 146-100 Statesman
$env:AIRCRAFT_TYPES_EXCL2+=",B462" #BRITISH AEROSPACE 146-200 Quiet Trader
$env:AIRCRAFT_TYPES_EXCL2+=",B463" #BRITISH AEROSPACE 146-300
$env:AIRCRAFT_TYPES_EXCL2+=",BDOG" #BRITISH AEROSPACE SA-3 Bulldog
$env:AIRCRAFT_TYPES_EXCL2+=",JS31" #BRITISH AEROSPACE Jetstream T.Mk.3
$env:AIRCRAFT_TYPES_EXCL2+=",JS32" #BRITISH AEROSPACE Jetstream Super 31
$env:AIRCRAFT_TYPES_EXCL2+=",JS41" #BRITISH AEROSPACE Jetstream 41


#Boeing
$env:AIRCRAFT_TYPES_EXCL2+=",B712"
$env:AIRCRAFT_TYPES_EXCL2+=",B722" #BOEING 727-200
$env:AIRCRAFT_TYPES_EXCL2+=",B732" #BOEING 737-200
$env:AIRCRAFT_TYPES_EXCL2+=",B733" #BOEING 737-300
$env:AIRCRAFT_TYPES_EXCL2+=",B734" #BOEING 737-400
$env:AIRCRAFT_TYPES_EXCL2+=",B735" #BOEING 737-500
$env:AIRCRAFT_TYPES_EXCL2+=",B736" #BOEING 737-600
$env:AIRCRAFT_TYPES_EXCL+=",B737" #BOEING 737-700
$env:AIRCRAFT_TYPES_CONFIRMED+=",E737" #Boeing E-7A Wedgetail
$env:AIRCRAFT_TYPES_EXCL2+=",B37M" #BOEING 737 MAX 7
$env:AIRCRAFT_TYPES_EXCL+=",B738" #BOEING 737-800
$env:AIRCRAFT_TYPES_EXCL+=",B38M" #BOEING 737 MAX 8
$env:AIRCRAFT_TYPES_CONFIRMED+=",P8" #Boeing P8 Posidon
$env:AIRCRAFT_TYPES_CONFIRMED+=",P8-?" #
$env:AIRCRAFT_TYPES_EXCL2+=",B739" #BOEING 737-900
$env:AIRCRAFT_TYPES_EXCL2+=",B39M" #BOEING 737 MAX 9
$env:AIRCRAFT_TYPES_EXCL2+=",B3XM" #BOEING 737 MAX 10
$env:AIRCRAFT_TYPES_CONFIRMED+=",B742" #Boeing E-4B
$env:AIRCRAFT_TYPES_CONFIRMED+=",B743" #BOEING 747-300
$env:AIRCRAFT_TYPES_EXCL2+=",B744" #BOEING 747-400
$env:AIRCRAFT_TYPES_CONFIRMED+=",BLCF" #BOEING 747-400LCF Dreamlifter
$env:AIRCRAFT_TYPES_EXCL2+=",B748" #BOEING 747-8
$env:AIRCRAFT_TYPES_EXCL2+=",B752" #Boeing C-32A
$env:AIRCRAFT_TYPES_EXCL2+=",B753" #BOEING 757-300
$env:AIRCRAFT_TYPES_EXCL2+=",B762" #KC46??
$env:AIRCRAFT_TYPES_EXCL2+=",B763" #BOEING 767-300
$env:AIRCRAFT_TYPES_EXCL2+=",B764" #BOEING 767-400
$env:AIRCRAFT_TYPES_EXCL2+=",B772" #BOEING 777-200
$env:AIRCRAFT_TYPES_EXCL2+=",B77L" #BOEING 777-200LR
$env:AIRCRAFT_TYPES_EXCL2+=",B773" #BOEING 777-300
$env:AIRCRAFT_TYPES_EXCL2+=",B77W" #BOEING 777-300ER
$env:AIRCRAFT_TYPES_CONFIRMED+=",B779" #BOEING 777-9
$env:AIRCRAFT_TYPES_EXCL2+=",B788" #BOEING 787-8 Dreamliner
$env:AIRCRAFT_TYPES_EXCL2+=",B789" #BOEING 787-9 Dreamliner
$env:AIRCRAFT_TYPES_EXCL2+=",B78X" #BOEING 787-10 Dreamliner
#Boeing Military Jets
$env:AIRCRAFT_TYPES_CONFIRMED+=",B703" #BOEING 707-300
$env:AIRCRAFT_TYPES_EXCL2+=",E3TF" #Boeing E-3G Sentry
$env:AIRCRAFT_TYPES_EXCL2+=",E3CF" #Boeing E-3F Sentry
#$env:AIRCRAFT_TYPES_EXCL2+=",E6B" #boring at high
$env:AIRCRAFT_TYPES_EXCL2+=",E6" #Boeing E-6B Mercury
$env:AIRCRAFT_TYPES_EXCL2+=",K35R" #BOEING KC-135R/T Stratotanker
$env:AIRCRAFT_TYPES_CONFIRMED+=",W135" #Boeing WC-135R Constant Phoenix
$env:AIRCRAFT_TYPES_CONFIRMED+=",R135"
#Boeing Special
$env:AIRCRAFT_TYPES_EXCL2+=",BT7" #Boeing T-7A Red Hawk
$env:AIRCRAFT_TYPES_CONFIRMED+=",B52"
$env:AIRCRAFT_TYPES_CONFIRMED+=",V22"
$env:AIRCRAFT_TYPES_CONFIRMED+=",F18S" #Boeing EA-18G Growler

#BOLKOW
$env:AIRCRAFT_TYPES_CONFIRMED+=",KL07" #BOLKOW BO-107
$env:AIRCRAFT_TYPES_EXCL2+=",JUNR" #BOLKOW BO-208 Junior

#Burt Rutan / Canaards
$env:AIRCRAFT_TYPES_EXCL2+=",ERAC" #DICKEY E-Racer
$env:AIRCRAFT_TYPES_EXCL2+=",BKUT" #BERKUT Berkut Candard

$env:AIRCRAFT_TYPES_EXCL2+=",VEZE" #RUTAN VeriEasy
$env:AIRCRAFT_TYPES_EXCL2+=",LGEZ" #RUTAN Long-EZ
$env:AIRCRAFT_TYPES_EXCL2+=",DEFI" #RUTAN 40 Defiant #cool push pull
$env:AIRCRAFT_TYPES_EXCL2+=",VELO" #Velocity
$env:AIRCRAFT_TYPES_EXCL2+=",COZY" #CO-Z Cozy
$env:AIRCRAFT_TYPES_EXCL2+=",QIC2" #QUICKIE Q2


#BUSHBY
$env:AIRCRAFT_TYPES_EXCL2+=",MIMU" #BUSHBY Midget Mustang
$env:AIRCRAFT_TYPES_EXCL2+=",MUS2" #BUSHBY M-2 Mustang 2

#Briatan Norman
$env:AIRCRAFT_TYPES_CONFIRMED+=",BN2P" #Islander
$env:AIRCRAFT_TYPES_CONFIRMED+=",BN2T" #BRITTEN-NORMAN BN-2T Turbine Islander

##Bellanca
$env:AIRCRAFT_TYPES_EXCL+=",CH7B" #BELLANCA 7 Citabria
$env:AIRCRAFT_TYPES_EXCL+=",CH7A" #BELLANCA 7 Champion
$env:AIRCRAFT_TYPES_EXCL+=",BL8" #BELLANCA 8 Decathlon
$env:AIRCRAFT_TYPES_EXCL+=",B14A" #BELLANCA 14
$env:AIRCRAFT_TYPES_EXCL+=",BL17" #BELLANCA 17 Viking

##beachcraft
#Singles
$env:AIRCRAFT_TYPES_EXCL2+=",BE17" #BEECH 17 Staggerwing
$env:AIRCRAFT_TYPES_EXCL+=",BE19" #BEECH 19 Sport
$env:AIRCRAFT_TYPES_EXCL+=",BE23" #BEECH 23 Sundowner
$env:AIRCRAFT_TYPES_EXCL+=",BE24" #BEECH 24 Sierra
$env:AIRCRAFT_TYPES_EXCL+=",BE33" #BEECH 33 Bonanza
$env:AIRCRAFT_TYPES_EXCL+=",BE35" #BEECH 35 Bonanza
$env:AIRCRAFT_TYPES_EXCL+=",BE36" #BEECH 36 Bonanza
$env:AIRCRAFT_TYPES_EXCL+=",BT36" #BEECH B36TC Bonanza
$env:AIRCRAFT_TYPES_EXCL+=",T34T" #Beech T-34C Mentor
$env:AIRCRAFT_TYPES_EXCL+=",T34P" #BEECH T-34 Mentor
$env:AIRCRAFT_TYPES_EXCL+=",BE77" #BEECH 77 Skiper
#Twins
$env:AIRCRAFT_TYPES_EXCL2+=",BE18" #BEECH 18 Expetitor
$env:AIRCRAFT_TYPES_EXCL2+=",BE50" #BEECH 50 Excalibur
$env:AIRCRAFT_TYPES_EXCL+=",BE55" #BEECH 55 Baron
$env:AIRCRAFT_TYPES_EXCL+=",BE56" #BEECH 56 Turbo Baron
$env:AIRCRAFT_TYPES_EXCL+=",BE58" #BEECH 58 Baron
$env:AIRCRAFT_TYPES_EXCL+=",B58T" #BEECH 58TC Baron
$env:AIRCRAFT_TYPES_EXCL+=",BE76" #BEECH 76 Duchess
$env:AIRCRAFT_TYPES_EXCL+=",BE60" #BEECH 60 Duke
$env:AIRCRAFT_TYPES_EXCL+=",BE65" #BEECH 65 Queen Air
$env:AIRCRAFT_TYPES_EXCL+=",BE95" #BEECH 95 Travel Air
##TurboProps
#Beach Twinds
$env:AIRCRAFT_TYPES_EXCL+=",BE9T" #BEECH F90 King Air
$env:AIRCRAFT_TYPES_EXCL+=",BE9L" #BEECH 90 King Air
$env:AIRCRAFT_TYPES_EXCL+=",BE10" #BEECH 100 King Air
$env:AIRCRAFT_TYPES_EXCL+=",BE20" #BEECH 200 Super King Air
$env:AIRCRAFT_TYPES_EXCL+=",BE30" #BEECH 300 Super King Air
$env:AIRCRAFT_TYPES_EXCL+=",BE99" #BEECH 99 Airliner
$env:AIRCRAFT_TYPES_EXCL+=",B350" #BEECHCRAFT Super King Air 350
$env:AIRCRAFT_TYPES_EXCL+=",B190" #BEECH 1900
#Beach Singles
$env:AIRCRAFT_TYPES_EXCL+=",B36T" #BEECH 36 Turbine Bonanza
$env:AIRCRAFT_TYPES_EXCL+=",BE22" #BEECHCRAFT 220 Denali
#Beach Jets
$env:AIRCRAFT_TYPES_EXCL+=",BE40" #Beechcraft T-1A Jayhawk
$env:AIRCRAFT_TYPES_EXCL+=",PRM1" #Beechcraft Hawker RAYTHEON 390 Premier 1
$env:AIRCRAFT_TYPES_EXCL+=",BE4W" #BEECH 400XT Beechjet
$env:AIRCRAFT_TYPES_EXCL+=",HA4T" #Beechcraft RAYTHEON 4000 Hawker Horizon
$env:AIRCRAFT_TYPES_EXCL+=",H25C" #Beechcraft RAYTHEON Hawker 1000

#BEST OFF
$env:AIRCRAFT_TYPES_EXCL2+=",SKRA" #BEST OFF Sky Ranger
$env:AIRCRAFT_TYPES_EXCL2+=",NNJA" #BEST OFF Nynja

#BRM AERO 
$env:AIRCRAFT_TYPES_EXCL2+=",NG4" #BRM AERO NG-4
$env:AIRCRAFT_TYPES_EXCL2+=",NG5" #BRM AERO NG-5/6 Bristell
$env:AIRCRAFT_TYPES_EXCL2+=",BR23" #BRM AERO Bristell B23


#CENTRE
$env:AIRCRAFT_TYPES_EXCL2+=",DR10" #CENTRE EST Ambassadeur
$env:AIRCRAFT_TYPES_EXCL2+=",DR30" #CENTRE EST Prince
$env:AIRCRAFT_TYPES_EXCL2+=",DR22" #CENTRE EST DR.221 Dauphin
$env:AIRCRAFT_TYPES_EXCL2+=",D250" #CENTRE EST DR-250 Captaine
$env:AIRCRAFT_TYPES_EXCL2+=",D253" #CENTRE EST DR-253 Regent



##Cessna
#Small singles
$env:AIRCRAFT_TYPES_EXCL+=",C120" #CESSNA 120
$env:AIRCRAFT_TYPES_EXCL+=",C140" #CESSNA 140
$env:AIRCRAFT_TYPES_EXCL+=",C152" #CESSNA 152
$env:AIRCRAFT_TYPES_EXCL+=",C150" #CESSNA 150
$env:AIRCRAFT_TYPES_EXCL+=",C162" #CESSNA 162 Skycatcher
$env:AIRCRAFT_TYPES_EXCL+=",C170" #CESSNA 170
$env:AIRCRAFT_TYPES_EXCL+=",C172" #CESSNA 172 Skyhawk
$env:AIRCRAFT_TYPES_EXCL+=",C72R" #CESSNA 172R Cutlass RG
$env:AIRCRAFT_TYPES_EXCL+=",C175" #CESSNA 175 Skylark
$env:AIRCRAFT_TYPES_EXCL+=",C177" #CESSNA  177 Cardinal
$env:AIRCRAFT_TYPES_EXCL+=",C77R" #CESSNA 177RG Cardinal RG
$env:AIRCRAFT_TYPES_EXCL+=",C185" #CESSNA 185 Skywagon
$env:AIRCRAFT_TYPES_EXCL+=",C180" #CESSNA  180 Skywagon
$env:AIRCRAFT_TYPES_EXCL+=",C182" #CESSNA 182 Skylane
$env:AIRCRAFT_TYPES_EXCL+=",C82S" #CESSNA T182 Turbo Skylane
$env:AIRCRAFT_TYPES_EXCL+=",C82R" #CESSNA R182 Skylane RG
$env:AIRCRAFT_TYPES_EXCL+=",C82T" #CESSNA TR182 Turbo Skylane RG
$env:AIRCRAFT_TYPES_EXCL2+=",C188" #CESSNA 188 AgTruck
$env:AIRCRAFT_TYPES_EXCL+=",C190" #CESSNA 190
$env:AIRCRAFT_TYPES_EXCL2+=",C195" #CESSNA 195
$env:AIRCRAFT_TYPES_EXCL+=",COL3" #CESSNA 350 Corvalis
$env:AIRCRAFT_TYPES_EXCL+=",COL4" #CESSNA 400 Corvalis TT
#Large Singles
$env:AIRCRAFT_TYPES_EXCL+=",C206" #CESSNA  206 Stationair
$env:AIRCRAFT_TYPES_EXCL+=",T206" #CESSNA T206 Turbo Stationair
$env:AIRCRAFT_TYPES_EXCL+=",C207" #CESSNA 207 Turbo Stationair
$env:AIRCRAFT_TYPES_EXCL+=",C210" #CESSNA 201 Centurion
$env:AIRCRAFT_TYPES_EXCL+=",P210" #CESSNA P210 Centurion
$env:AIRCRAFT_TYPES_EXCL+=",T210" #CESSNA T210 Turbo Centurion
$env:AIRCRAFT_TYPES_EXCL+=",C240" #CESSNA 240 Corvalis TTx
#Twins
$env:AIRCRAFT_TYPES_EXCL2+=",O1" #CESSNA 305/341 Bird Dog
$env:AIRCRAFT_TYPES_EXCL2+=",T50" #CESSNA Bobcat

#$env:AIRCRAFT_TYPES_EXCL+=",C320,C335"
$env:AIRCRAFT_TYPES_EXCL+=",C320" #CESSNA 320 Skyknight
$env:AIRCRAFT_TYPES_EXCL+=",C310" #CESSNA 310
$env:AIRCRAFT_TYPES_EXCL2+=",C337" #Skymaster
$env:AIRCRAFT_TYPES_EXCL2+=",P337" #CESSNA P337 Skymaster
$env:AIRCRAFT_TYPES_EXCL+=",C335" #CESSNA 335 (unpressurized 340)
$env:AIRCRAFT_TYPES_EXCL+=",C340" #CESSNA 340 Super
$env:AIRCRAFT_TYPES_EXCL+=",C404" #CESSNA 404 Titan
$env:AIRCRAFT_TYPES_EXCL+=",C402" #CESSNA 402 Businessliner
$env:AIRCRAFT_TYPES_EXCL+=",F406" #CESSNA F406 Caravan 2
$env:AIRCRAFT_TYPES_EXCL+=",C414" #CESSNA 414 Chancellor
$env:AIRCRAFT_TYPES_EXCL+=",C421" #CESSNA 421 Executive Commuter
$env:AIRCRAFT_TYPES_EXCL+=",C425" #CESSNA 425 Corsair
$env:AIRCRAFT_TYPES_EXCL+=",C441" #CESSNA 441 Conquest
$env:AIRCRAFT_TYPES_EXCL+=",C303" #CESSNA T303 Crusader
#Turbines
$env:AIRCRAFT_TYPES_EXCL+=",C208" #CESSNA 208 Caravan
$env:AIRCRAFT_TYPES_EXCL+=",C10T" #CESSNA P210 Turbine
$env:AIRCRAFT_TYPES_EXCL+=",C408" #CESSNA 408 SkyCourier
#Cessna Jets
#$env:AIRCRAFT_TYPES_EXCL+=",CJ4"
$env:AIRCRAFT_TYPES_EXCL+=",C25A" #CESSNA 525A Citation CJ2
$env:AIRCRAFT_TYPES_EXCL+=",C25B" #CESSNA 525B Citation CJ3
$env:AIRCRAFT_TYPES_EXCL+=",C25C" #CESSNA 525C Citation CJ4
$env:AIRCRAFT_TYPES_EXCL+=",C25M" #CESSNA 525 Citation M2
$env:AIRCRAFT_TYPES_EXCL+=",C510" #CESSNA 510 Citation Mustang
$env:AIRCRAFT_TYPES_EXCL+=",C500" #CESSNA 500 Citation 1
$env:AIRCRAFT_TYPES_EXCL+=",C501" #CESSNA 501 Citation 1SP
$env:AIRCRAFT_TYPES_EXCL+=",C525" #CESSNA 525 CitationJet
$env:AIRCRAFT_TYPES_EXCL+=",C550" #CESSNA 550 Citation S2
$env:AIRCRAFT_TYPES_EXCL+=",C560" #CESSNA 560 Citation Ultra
$env:AIRCRAFT_TYPES_EXCL+=",C55B" #CESSNA 550B Citation Bravo
$env:AIRCRAFT_TYPES_EXCL+=",C551" #CESSNA 551 Citation 2SP
$env:AIRCRAFT_TYPES_EXCL+=",C56X" #CESSNA 560XL Citation XLS
$env:AIRCRAFT_TYPES_EXCL+=",C650" #CESSNA 650 Citation
$env:AIRCRAFT_TYPES_EXCL+=",C68A" #CESSNA 680 Citation Latitude
$env:AIRCRAFT_TYPES_EXCL+=",C680" #CESSNA 680 Citation Sovereign
$env:AIRCRAFT_TYPES_EXCL+=",C700" #CESSNA 700 Citation Longitude
$env:AIRCRAFT_TYPES_EXCL+=",C750" #CESSNA 750 Citation 10

##Cirus
$env:AIRCRAFT_TYPES_EXCL+=",SR20" #Cirrus T-53A Kaydet II
$env:AIRCRAFT_TYPES_EXCL+=",SR22" #CIRRUS SR-22
$env:AIRCRAFT_TYPES_EXCL+=",S22T" #CIRRUS SR-22T Turbo
#Jets
$env:AIRCRAFT_TYPES_EXCL+=",SF50" #CIRRUS SF-50 Vision

#Candiair Private Jets
$env:AIRCRAFT_TYPES_EXCL+=",CL30" #BOMBARDIER BD-100 Challenger 300
$env:AIRCRAFT_TYPES_EXCL+=",CL35" #BOMBARDIER BD-100 Challenger 350
$env:AIRCRAFT_TYPES_EXCL+=",CL64" #
$env:AIRCRAFT_TYPES_EXCL+=",CL60" #BOMBARDIER CL-600 Challenger
$env:AIRCRAFT_TYPES_EXCL+=",CL65" #
#Candiar Regional Jets
$env:AIRCRAFT_TYPES_EXCL2+=",CRJ1" #BOMBARDIER Regional Jet CRJ-100
$env:AIRCRAFT_TYPES_EXCL+=",CRJ2" #BOMBARDIER Regional Jet CRJ-200
$env:AIRCRAFT_TYPES_EXCL+=",CRJ7" #BOMBARDIER Regional Jet CRJ-700
$env:AIRCRAFT_TYPES_EXCL2+=",CRJ9" #BOMBARDIER Regional Jet CRJ-900
$env:AIRCRAFT_TYPES_EXCL2+=",CRJX" #BOMBARDIER Regional Jet CRJ-1000
#other Canidair
$env:AIRCRAFT_TYPES_EXCL2+=",CVLT" #CANADAIR Cosmopolitan
$env:AIRCRAFT_TYPES_EXCL2+=",CL2P" #CANADAIR CL-215
$env:AIRCRAFT_TYPES_EXCL2+=",CL2T" #CANADAIR CL-415 SuperScooper


#CASA
$env:AIRCRAFT_TYPES_EXCL2+=",C212" #CASA-212-200
$env:AIRCRAFT_TYPES_CONFIRMED+=",CN35" #CASA HC-144B Ocean Sentry
$env:AIRCRAFT_TYPES_CONFIRMED+=",C295" #CASA C-295 Persuader

#Daher Kodiak
$env:AIRCRAFT_TYPES_EXCL2+=",K100" #Daher Kodiak
$env:AIRCRAFT_TYPES_EXCL+=",K900" #KODIAK QUEST 200/900

#DASSAULT Falcon
$env:AIRCRAFT_TYPES_EXCL2+=",F2EX" #
$env:AIRCRAFT_TYPES_EXCL2+=",F2LX" #
$env:AIRCRAFT_TYPES_EXCL+=",F2TH" #DASSAULT Falcon 2000
$env:AIRCRAFT_TYPES_EXCL+=",FA7X" #DASSAULT Falcon 7X
$env:AIRCRAFT_TYPES_EXCL+=",FA8X" #DASSAULT Falcon 8X
$env:AIRCRAFT_TYPES_EXCL+=",FA10" #DASSAULT Falcon 100
$env:AIRCRAFT_TYPES_EXCL+=",FA20" #DASSAULT Falcon 200
$env:AIRCRAFT_TYPES_EXCL+=",FA50" #DASSAULT Falcon 50
$env:AIRCRAFT_TYPES_EXCL+=",FA6X" #DASSAULT Falcon 6X
$env:AIRCRAFT_TYPES_EXCL+=",F900" #DASSAULT Falcon 900
$env:AIRCRAFT_TYPES_EXCL+=",F9EX" #Falcon 900EX
#$env:AIRCRAFT_TYPES_EXCL+=",F9LX"
#Fighters
$env:AIRCRAFT_TYPES_CONFIRMED+=",MRF1" #DASSAULT Mirage F1
$env:AIRCRAFT_TYPES_CONFIRMED+=",AJET" #DASSAULT-DORNIER Alpha Jet

#DE HAVILLAND
$env:AIRCRAFT_TYPES_CONFIRMED+=",DH89" #DE HAVILLAND Dragon Rapide
$env:AIRCRAFT_TYPES_EXCL2+=",DHC1" #DE HAVILLAND DHC-1 Chipmunk
$env:AIRCRAFT_TYPES_EXCL2+=",DHC2" #De Havilland U-6A Beaver
$env:AIRCRAFT_TYPES_EXCL2+=",DH2T" #DE HAVILLAND DHC-2 Turbo Beaver
$env:AIRCRAFT_TYPES_EXCL2+=",DHC3" #DE HAVILLAND DHC-3 Otter
$env:AIRCRAFT_TYPES_EXCL2+=",DH3T" #DE HAVILLAND DHC-3 Turbo otter
$env:AIRCRAFT_TYPES_CONFIRMED+=",DHC4" #DE HAVILLAND DHC-4 Caribou
$env:AIRCRAFT_TYPES_CONFIRMED+=",DH4T" #Turbo Caribou
$env:AIRCRAFT_TYPES_EXCL2+=",DHC6" #DE HAVILLAND DHC-6 Twin Otter
$env:AIRCRAFT_TYPES_EXCL2+=",DHC7" #DE HAVILLAND DHC-7 Dash 7
$env:AIRCRAFT_TYPES_EXCL2+=",DH8A" #DE HAVILLAND DHC-8-100 Dash 8
$env:AIRCRAFT_TYPES_EXCL2+=",DH8B" #DE HAVILLAND DHC-8-200 Dash 8
$env:AIRCRAFT_TYPES_EXCL2+=",DH8C" #DE HAVILLAND DHC-8-300 Dash 8
$env:AIRCRAFT_TYPES_EXCL2+=",DH8D" #DE HAVILLAND DHC-8-400 Dash 8

#Dornier
$env:AIRCRAFT_TYPES_EXCL2+=",D228" #DORNIER 228
$env:AIRCRAFT_TYPES_EXCL2+=",J328" #Dornier 328 JET
$env:AIRCRAFT_TYPES_EXCL2+=",D328" #Dornier C-146A Wolfhound

##Diamond
$env:AIRCRAFT_TYPES_EXCL+=",DV20" #DIAMOND DA-20
$env:AIRCRAFT_TYPES_EXCL+=",DIMO" #DIAMOND H-36 Dimona
$env:AIRCRAFT_TYPES_EXCL+=",DA40" #DIAMOND DA-40 Club Star
$env:AIRCRAFT_TYPES_EXCL+=",DA42" #DIAMOND DA-42 Guardian
$env:AIRCRAFT_TYPES_EXCL+=",DA50" #DIAMOND DA-50 Magnum
$env:AIRCRAFT_TYPES_EXCL+=",DA62" #DIAMOND DA-62

#DOVA
$env:AIRCRAFT_TYPES_EXCL2+=",DV1" #DOVA Skylark
$env:AIRCRAFT_TYPES_EXCL2+=",DV2" #DOVA Infinity

#Eclipse
$env:AIRCRAFT_TYPES_EXCL+=",EA50"

#Embrear 
#Private Jets 
$env:AIRCRAFT_TYPES_EXCL+=",E50P" #EMBRAER EMB-500 Phenom 100
$env:AIRCRAFT_TYPES_EXCL+=",E55P" #EMBRAER EMB-505 Phenom 300
$env:AIRCRAFT_TYPES_EXCL+=",E545" #EMBRAER EMB545 Praetor 500
$env:AIRCRAFT_TYPES_EXCL+=",E550" #EMBRAER EMB-550 Praetor 600
#Turboprops
$env:AIRCRAFT_TYPES_EXCL2+=",E110" #EMBRAER EMB-110 Bandeirante
$env:AIRCRAFT_TYPES_EXCL2+=",E120" #EMBRAER EMB-120 Brasilia
$env:AIRCRAFT_TYPES_EXCL2+=",E121" #EMBRAER EMB-121 Xingu
#Regional Jets
$env:AIRCRAFT_TYPES_EXCL+=",E135" #EMBRAER ERJ-135
$env:AIRCRAFT_TYPES_EXCL+=",E35L" #EMBRAER EMB-135 Legacy
$env:AIRCRAFT_TYPES_EXCL+=",E145" #EMBRAER ERJ-145
$env:AIRCRAFT_TYPES_EXCL+=",E45X" #EMBRAER ERJ-145XR
$env:AIRCRAFT_TYPES_EXCL2+=",E170" #EMBRAER ERJ-170-100
$env:AIRCRAFT_TYPES_EXCL2+=",E75S" #intersting to see difference?
$env:AIRCRAFT_TYPES_EXCL+=",E75L" #EMBRAER ERJ-170-200 (long wing)
$env:AIRCRAFT_TYPES_EXCL2+=",E195" #EMBRAER ERJ-190-200
$env:AIRCRAFT_TYPES_EXCL2+=",E190" #EMBRAER ERJ-190-100
$env:AIRCRAFT_TYPES_EXCL2+=",E290" #EMBRAER ERJ-190-300
$env:AIRCRAFT_TYPES_EXCL2+=",E295" #EMBRAER ERJ-190-400
#Embrear Military
$env:AIRCRAFT_TYPES_EXCL2+=",TUCA" #EMBRAER EMB-312 Tucano
$env:AIRCRAFT_TYPES_EXCL2+=",E314" #EMBRAER EMB-314 Super Tucano
$env:AIRCRAFT_TYPES_EXCL2+=",E390" #Embraer KC-390 Millennium

#EUROFIGHTER
$env:AIRCRAFT_TYPES_CONFIRMED+=",EUFI" #EUROFIGHTER 2000

#EVEKTRO
$env:AIRCRAFT_TYPES_EXCL+=",EV97" #EVEKTRO EV-97 EuroStar
$env:AIRCRAFT_TYPES_EXCL+=",EVSS" #EVEKTOR SportStar

#Fairchild Republic
$env:AIRCRAFT_TYPES_CONFIRMED+=",FA24" #FAIRCHILD F-24 Argus
$env:AIRCRAFT_TYPES_CONFIRMED+=",A10" #Fairchild A-10A Thunderbolt II
$env:AIRCRAFT_TYPES_EXCL2+=",FA62" #FAIRCHILD M-26 Cornell
#sea Plane
$env:AIRCRAFT_TYPES_EXCL2+=",RC3" #REPUBLIC RC-3 Seabee

#FOKKER 
#turboprop
$env:AIRCRAFT_TYPES_EXCL2+=",F50" #FOKKER 50
#Jet
$env:AIRCRAFT_TYPES_EXCL2+=",F70" #FOKKER 70
$env:AIRCRAFT_TYPES_EXCL2+=",F100" #FOKKER 100

#FOURNIER
$env:AIRCRAFT_TYPES_EXCL2+=",RF5" #FOURNIER RF-5
$env:AIRCRAFT_TYPES_EXCL2+=",RF6" #FOURNIER RF-6
$env:AIRCRAFT_TYPES_EXCL2+=",RF10" #FOURNIER RF-10

#FLIGHT DESIGN 
$env:AIRCRAFT_TYPES_EXCL+=",FDCT" #FLIGHT DESIGN CT
$env:AIRCRAFT_TYPES_EXCL+=",FDF2" #FLIGHT DESIGN F-2
$env:AIRCRAFT_TYPES_EXCL+=",FDMC" #FLIGHT DESIGN MC

#Glasair
$env:AIRCRAFT_TYPES_EXCL+=",GLAS" #Glasair
$env:AIRCRAFT_TYPES_EXCL+=",GLST" #GLASAIR SH-4 GlaStar
$env:AIRCRAFT_TYPES_EXCL+=",GLSP" #NEW GLASTAR Sportsman 2+2

#GROB
$env:AIRCRAFT_TYPES_EXCL2+=",G103" #GROB G-103 Twin 3SL
$env:AIRCRAFT_TYPES_EXCL2+=",G109" #GROB G-109
$env:AIRCRAFT_TYPES_EXCL2+=",G12T" #GROB G-120TP
$env:AIRCRAFT_TYPES_EXCL2+=",G115" #GROB G-115
$env:AIRCRAFT_TYPES_EXCL2+=",G120" #GROB G-120

#GROPPO
$env:AIRCRAFT_TYPES_EXCL2+=",G70" #GROPPO G-70
$env:AIRCRAFT_TYPES_EXCL2+=",TRAL" #GROPPO Trail


#Gliders
#$env:AIRCRAFT_TYPES_EXCL2+=",JS3J,ARCE"
$env:AIRCRAFT_TYPES_EXCL2+=",GLID" #ASTIR CS77X
$env:AIRCRAFT_TYPES_EXCL2+=",EB29" #BINDER EB-29
$env:AIRCRAFT_TYPES_EXCL2+=",PK20" #PIK 20E
$env:AIRCRAFT_TYPES_EXCL2+=",DISC" #SCHEMPP-HIRTH Discus
$env:AIRCRAFT_TYPES_EXCL2+=",DUOD" #SCHEMPP-HIRTH Duo Discus
$env:AIRCRAFT_TYPES_EXCL2+=",ARCP" #SCHEMPP-HIRTH Arcus M
$env:AIRCRAFT_TYPES_EXCL2+=",ARCE" #SCHEMPP-HIRTH Arcus E
$env:AIRCRAFT_TYPES_EXCL2+=",VENT" #SCHEMPP-HIRTH Ventus
$env:AIRCRAFT_TYPES_EXCL2+=",NIMB" #SCHEMPP-HIRTH Nimbus
$env:AIRCRAFT_TYPES_EXCL2+=",JANU" #SCHEMPP-HIRTH Janus
$env:AIRCRAFT_TYPES_EXCL2+=",LS8" #ROLLADEN-SCHNEIDER LS-8T
$env:AIRCRAFT_TYPES_EXCL2+=",AS16" #SCHLEICHER ASK-16
$env:AIRCRAFT_TYPES_EXCL2+=",AS20" #SCHLEICHER ASW-20
$env:AIRCRAFT_TYPES_EXCL2+=",AS21" #SCHLEICHER ASK-21
$env:AIRCRAFT_TYPES_EXCL2+=",AS24" #SCHLEICHER ASW-24
$env:AIRCRAFT_TYPES_EXCL2+=",AS25" #SCHLEICHER ASH-25
$env:AIRCRAFT_TYPES_EXCL2+=",AS26" #SCHLEICHER ASH-26
$env:AIRCRAFT_TYPES_EXCL2+=",AS28" #SCHLEICHER ASW-28
$env:AIRCRAFT_TYPES_EXCL2+=",AS29" #SCHLEICHER ASG-29
$env:AIRCRAFT_TYPES_EXCL2+=",AS31" #SCHLEICHER ASH-31
$env:AIRCRAFT_TYPES_EXCL2+=",A33P" #SCHLEICHER AS-33Es
$env:AIRCRAFT_TYPES_EXCL2+=",DG40" #DG FLUGZEUGBAU DG-400
$env:AIRCRAFT_TYPES_EXCL2+=",DG60" #DG FLUGZEUGBAU DG-600M
$env:AIRCRAFT_TYPES_EXCL2+=",DG80" #DG FLUGZEUGBAU DG-800
$env:AIRCRAFT_TYPES_EXCL2+=",DG1T" #DG FLUGZEUGBAU DG-1001T
$env:AIRCRAFT_TYPES_EXCL2+=",AV68" #M&D FLUGZEUGBAU AVO-68 Samburo
$env:AIRCRAFT_TYPES_EXCL2+=",S10S" #STEMME S-10 Chrysalis
$env:AIRCRAFT_TYPES_EXCL2+=",S12S" #STEMME S 12 Glider
$env:AIRCRAFT_TYPES_EXCL2+=",LK17" #SPORTINE AVIACIJA LAK-17AT
$env:AIRCRAFT_TYPES_EXCL2+=",LK19" #SPORTINE AVIACIJA LAK-19T
$env:AIRCRAFT_TYPES_CONFIRMED+=",JS3E" #JONKER JS-3 Rapture !Electric
$env:AIRCRAFT_TYPES_CONFIRMED+=",JS3J" #JONKER JS-3 Rapture Jet
$env:AIRCRAFT_TYPES_EXCL2+=",LK7E" #LAK-17 FES


#Grumman
#military
$env:AIRCRAFT_TYPES_EXCL2+=",C2" #Grumman C-2A Greyhound
$env:AIRCRAFT_TYPES_EXCL2+=",E2" #Grumman E-2D Hawkeye
$env:AIRCRAFT_TYPES_CONFIRMED+=",S2P" #GRUMMAN S-2 Tracker
#ag
$env:AIRCRAFT_TYPES_EXCL2+=",G164" #GRUMMAN G-164 Ag-Cat
#Sea Planes
$env:AIRCRAFT_TYPES_EXCL2+=",U16" #GRUMMAN Albatross
$env:AIRCRAFT_TYPES_EXCL2+=",G21" #GRUMMAN G-21A Goose
$env:AIRCRAFT_TYPES_EXCL2+=",G44" #GRUMMAN G-44 Widgeon
$env:AIRCRAFT_TYPES_EXCL2+=",G73T" #GRUMMAN G-73T Turbo Mallard

#Gulfstream
$env:AIRCRAFT_TYPES_EXCL+=",ASTR" #IAI C-38A Courier IAI 1125 Astra/Gulfstream G100/G150
$env:AIRCRAFT_TYPES_EXCL+=",G150" #GULFSTREAM G150
$env:AIRCRAFT_TYPES_EXCL+=",GLF2" #GULFSTREAM 2
$env:AIRCRAFT_TYPES_EXCL+=",G200" #G200
$env:AIRCRAFT_TYPES_EXCL+=",GALX" #GULFSTREAM G200
$env:AIRCRAFT_TYPES_EXCL+=",G280" #GULFSTREAM G280
$env:AIRCRAFT_TYPES_EXCL+=",GLF3" #GULFSTREAM 3
$env:AIRCRAFT_TYPES_EXCL+=",GLF4" #GULFSTREAM 4
$env:AIRCRAFT_TYPES_EXCL+=",GA4C" #GULFSTREAM G-7 G400
$env:AIRCRAFT_TYPES_EXCL+=",G450" #GULFSTREAM G450
$env:AIRCRAFT_TYPES_EXCL+=",GLF5" #GULFSTREAM 5
$env:AIRCRAFT_TYPES_EXCL+=",GA5C" #GULFSTREAM G500
$env:AIRCRAFT_TYPES_EXCL+=",G550" #
$env:AIRCRAFT_TYPES_EXCL+=",GL5T" #BOMBARDIER BD-700 Global 5000/5500
$env:AIRCRAFT_TYPES_EXCL+=",GA6C" #GULFSTREAM G600
$env:AIRCRAFT_TYPES_EXCL+=",GL6T" #BOMBARDIER BD-700 Global 6000/6500
$env:AIRCRAFT_TYPES_EXCL+=",GLF6" #GULFSTREAM G650
$env:AIRCRAFT_TYPES_EXCL+=",G650" #GULFSTREAM G650
#$env:AIRCRAFT_TYPES_EXCL+="GALX"
$env:AIRCRAFT_TYPES_EXCL+=",GA7C" #GULFSTREAM G700
$env:AIRCRAFT_TYPES_EXCL+=",GLEX" #BOMBARDIER BD-700 Global 6000/6500
$env:AIRCRAFT_TYPES_EXCL+=",GL7T" #BOMBARDIER BD-700 Global 7000/7500
$env:AIRCRAFT_TYPES_EXCL2+=",GA8C" #GULFSTREAM G-8 G800

#Hawker
$env:AIRCRAFT_TYPES_EXCL+=",H25A" #HAWKER SIDDELEY HS-125
$env:AIRCRAFT_TYPES_EXCL+=",H25B" #HAWKER BEECHCRAFT Hawker 750/850
#miltiary
$env:AIRCRAFT_TYPES_CONFIRMED+=",HUNT" #HAWKER Hunter
$env:AIRCRAFT_TYPES_CONFIRMED+=",FURY" #HAWKER Fury

#JODEL
$env:AIRCRAFT_TYPES_EXCL2+=",D11" #JODEL D-11x/12x
$env:AIRCRAFT_TYPES_EXCL2+=",D140" #JODEL D-140 Mousquetaire
$env:AIRCRAFT_TYPES_EXCL2+=",D150" #JODEL D-150 Mascaret


#Jabiru
$env:AIRCRAFT_TYPES_EXCL+=",JABI" #Jabiru J120
$env:AIRCRAFT_TYPES_EXCL+=",JAB2" #JABIRU J160/170
$env:AIRCRAFT_TYPES_EXCL+=",JAB4" #JABIRU J200-450


#JUST 
$env:AIRCRAFT_TYPES_EXCL2+=",SSTL" #JUST JA30 SuperSTOL
$env:AIRCRAFT_TYPES_EXCL2+=",HIGH" #JUST JA20 Highlander

#JIHLAVAN 
$env:AIRCRAFT_TYPES_EXCL2+=",KP5" #JIHLAVAN KP-5 Skyleader
$env:AIRCRAFT_TYPES_EXCL2+=",J600" #JIHLAVAN Skyleader 600

#LANCAIR
#piston
$env:AIRCRAFT_TYPES_EXCL+=",LNCE" #LANCAIR ES
$env:AIRCRAFT_TYPES_EXCL+=",LESP" #LANCAIR ES-P
$env:AIRCRAFT_TYPES_EXCL+=",LNC2" #LANCAIR 200-320
$env:AIRCRAFT_TYPES_EXCL+=",LNC4" #LANCAIR 4
$env:AIRCRAFT_TYPES_EXCL+=",LEG2" #LANCAIR Legacy
#tuurboprop
$env:AIRCRAFT_TYPES_EXCL+=",LNP4" #LANCAIR PropJet 4
$env:AIRCRAFT_TYPES_EXCL+=",EVOP" #LANCAIR Evolution Piston
$env:AIRCRAFT_TYPES_EXCL+=",EVOT" #LANCAIR Evolution Turbine

#Lear
$env:AIRCRAFT_TYPES_EXCL+=",LJ24" #LEARJET 24
$env:AIRCRAFT_TYPES_EXCL+=",LJ25" #LEARJET 25
$env:AIRCRAFT_TYPES_EXCL+=",LJ35" #LEARJET 35
$env:AIRCRAFT_TYPES_EXCL+=",LJ31" #LEARJET 31
$env:AIRCRAFT_TYPES_EXCL+=",LJ40" #LEARJET 40
$env:AIRCRAFT_TYPES_EXCL+=",LJ45" #LEARJET 45
$env:AIRCRAFT_TYPES_EXCL+=",LJ55" #LEARJET 55
$env:AIRCRAFT_TYPES_EXCL+=",LJ60" #LEARJET 60
$env:AIRCRAFT_TYPES_EXCL+=",LJ70" #LEARJET 70
$env:AIRCRAFT_TYPES_EXCL+=",LJ75" #LEARJET 75

#LOCKHEED
$env:AIRCRAFT_TYPES_EXCL2+=",C130" #Lockheed C-130H Hercules
$env:AIRCRAFT_TYPES_EXCL2+=",C30J" #Lockheed Martin HC-130J Hercules
$env:AIRCRAFT_TYPES_EXCL2+=",C17" #boring at high
$env:AIRCRAFT_TYPES_CONFIRMED+=",C5M"
#cool/rare/old
$env:AIRCRAFT_TYPES_CONFIRMED+=",T33" #LOCKHEED T-33
$env:AIRCRAFT_TYPES_CONFIRMED+=",P2" #LOCKHEED Neptune
$env:AIRCRAFT_TYPES_CONFIRMED+=",L188" #LOCKHEED L-188 Electra
$env:AIRCRAFT_TYPES_EXCL2+=",P3" #Lockheed NP-3D Orion
$env:AIRCRAFT_TYPES_EXCL2+=",L12" #LOCKHEED L-12 Electra Junior
$env:AIRCRAFT_TYPES_EXCL2+=",L37" #LOCKHEED L-137 Ventura
$env:AIRCRAFT_TYPES_CONFIRMED+=",U2" #Lockheed ER-2
$env:AIRCRAFT_TYPES_CONFIRMED+=",F35" #Lockheed Martin F-35 Lightning II (Generic Code)


#MAULE
$env:AIRCRAFT_TYPES_EXCL+=",M4" #MAULE M-4
$env:AIRCRAFT_TYPES_EXCL+=",M5" #MAULE M-5
$env:AIRCRAFT_TYPES_EXCL+=",M6" #MAULE M-6
$env:AIRCRAFT_TYPES_EXCL+=",M7" #MAULE M-7

#MCDONNELL-DOUGLAS / DOUGLAS
$env:AIRCRAFT_TYPES_CONFIRMED+=",DC3" #DOUGLAS DC-3 Dakota
$env:AIRCRAFT_TYPES_CONFIRMED+=",DC3T" #DOUGLAS DC-3 Turbine Conversoin
$env:AIRCRAFT_TYPES_CONFIRMED+=",DC4" #DOUGLAS DC-4 Skymaster
$env:AIRCRAFT_TYPES_CONFIRMED+=",DC6" #DOUGLAS DC-6 Liftmaster
$env:AIRCRAFT_TYPES_CONFIRMED+=",DC87" #MCDONNELL DOUGLAS DC-8-70
$env:AIRCRAFT_TYPES_EXCL2+=",MD82" #MCDONNELL-DOUGLAS MD-82
$env:AIRCRAFT_TYPES_EXCL2+=",MD83" #MCDONNELL-DOUGLAS MD-83
$env:AIRCRAFT_TYPES_EXCL2+=",MD87" #MCDONNELL-DOUGLAS MD-87
$env:AIRCRAFT_TYPES_EXCL2+=",MD88" #MCDONNELL-DOUGLAS MD-88
#$env:AIRCRAFT_TYPES_EXCL2+=",MD90"
$env:AIRCRAFT_TYPES_EXCL2+=",DC91" #MCDONNELL DOUGLAS DC-9-10
$env:AIRCRAFT_TYPES_EXCL2+=",DC93" #MCDONNELL DOUGLAS DC-9-30
$env:AIRCRAFT_TYPES_EXCL2+=",DC10" #MCDONNELL DOUGLAS DC-10
$env:AIRCRAFT_TYPES_EXCL2+=",MD11"
$env:AIRCRAFT_TYPES_CONFIRMED+=",F15" #McDonnell Douglas F-15E Strike Eagle
$env:AIRCRAFT_TYPES_CONFIRMED+=",HAR" #McDonnell-Douglas AV-8B Harrier II+
$env:AIRCRAFT_TYPES_CONFIRMED+=",HAWK" #McDonnell Douglas T-45C Goshawk
$env:AIRCRAFT_TYPES_CONFIRMED+=",A4" #DOUGLAS A-4 Skyhawk

##Mooney
$env:AIRCRAFT_TYPES_EXCL+=",M10" #MOONEY M-10 Cadet
$env:AIRCRAFT_TYPES_EXCL+=",M20P" #MOONEY M-20P
$env:AIRCRAFT_TYPES_EXCL+=",M20T" #MOONEY M-20T
$env:AIRCRAFT_TYPES_EXCL+=",MM22" #Mooney M22 Mustang

#MITSUBISHI 
#turboprop
$env:AIRCRAFT_TYPES_EXCL2+=",MU2" #MITSUBISHI MU-2 Marquise
#Jet
$env:AIRCRAFT_TYPES_EXCL2+=",MU30" #MITSUBISHI MU-300 Diamond

#MILES 
$env:AIRCRAFT_TYPES_EXCL2+=",MAGI" #MILES Magister
$env:AIRCRAFT_TYPES_EXCL2+=",MESS" #MILES Messenger

#MURPHY 
$env:AIRCRAFT_TYPES_EXCL2+=",RBEL" #MURPHY Rebel
$env:AIRCRAFT_TYPES_EXCL2+=",MR35" #MURPHY SR-3500 Super Rebel




#Northrup
$env:AIRCRAFT_TYPES_CONFIRMED+=",F5" #Northrop F-5N Tiger II
$env:AIRCRAFT_TYPES_CONFIRMED+=",T38" #Northrop T-38A Talon

##Piper
#singles
$env:AIRCRAFT_TYPES_EXCL+=",J3" #PIPER J-3 Cub
$env:AIRCRAFT_TYPES_EXCL+=",J4" #PIPER J-4 Cub Coupe
$env:AIRCRAFT_TYPES_EXCL+=",J5" #PIPER J-5 Cub Cruiser
$env:AIRCRAFT_TYPES_EXCL+=",PA11" #PIPER PA-11 Cub Special
$env:AIRCRAFT_TYPES_EXCL+=",PA12" #PIPER PA-12 Super Cruiser
$env:AIRCRAFT_TYPES_EXCL+=",PA14" #PIPER PA-14 Family Cruiser
$env:AIRCRAFT_TYPES_EXCL+=",PA16" #PIPER PA-16 Clipper
$env:AIRCRAFT_TYPES_EXCL+=",PA17" #PIPER PA-17 Vagabond Trainer
$env:AIRCRAFT_TYPES_EXCL+=",PA18" #PIPER PA-18 Super Cub
$env:AIRCRAFT_TYPES_EXCL+=",PA20" #PIPER PA-20 Pacer
$env:AIRCRAFT_TYPES_EXCL+=",PA22" #PIPER PA-22
$env:AIRCRAFT_TYPES_EXCL+=",PA23" #PIPER PA-23
$env:AIRCRAFT_TYPES_EXCL+=",PA24" #PIPER PA-24 Comanche
$env:AIRCRAFT_TYPES_EXCL+=",PA25" #PIPER PA-25 Pawnee
$env:AIRCRAFT_TYPES_EXCL+=",PA27" #PIPER PA-23-250 Aztec
$env:AIRCRAFT_TYPES_EXCL+=",P28A" #PIPER PA-28-140/150/160/180
$env:AIRCRAFT_TYPES_EXCL+=",P28B" #PIPER PA-28-201T/235/236
$env:AIRCRAFT_TYPES_EXCL+=",P28R" #PIPER PA-28R-180/200/201
$env:AIRCRAFT_TYPES_EXCL+=",P28S" #PIPER PA-28R-201T
$env:AIRCRAFT_TYPES_EXCL+=",P28T" #PIPER PA-28RT-201
$env:AIRCRAFT_TYPES_EXCL+=",P28U" #PIPER PA-28RT-201T Turbo
$env:AIRCRAFT_TYPES_EXCL+=",PA31" #PIPER PA-31-300/310/325/350/425
$env:AIRCRAFT_TYPES_EXCL+=",PAY1" #PIPER PA-31T1-500 Cheyenne 1
$env:AIRCRAFT_TYPES_EXCL+=",PAY2" #PIPER PA-31T2-620 Cheyenne 2
$env:AIRCRAFT_TYPES_EXCL+=",PA32" #PIPER PA-32
$env:AIRCRAFT_TYPES_EXCL+=",P32T" #PIPER PA-32RT-300/300T
$env:AIRCRAFT_TYPES_EXCL+=",P32R" #PIPER PA-32R-300/301/301T
$env:AIRCRAFT_TYPES_EXCL+=",PA34" #PIPER PA-34 Seneca
$env:AIRCRAFT_TYPES_EXCL+=",PA38" #PIPER PA-38 Tomahawk
$env:AIRCRAFT_TYPES_EXCL+=",PAY3" #PIPER PA-42-720 Cheyenne 3
$env:AIRCRAFT_TYPES_EXCL+=",PAY4" #PIPER PA-42-1000 Cheyenne 400
$env:AIRCRAFT_TYPES_EXCL+=",PA46" #PIPER PA-46-310/350
$env:AIRCRAFT_TYPES_EXCL+=",P46T" #PIPER PA-46-500TP
$env:AIRCRAFT_TYPES_EXCL+=",M600" #PIPER PA-46-600TP
$env:AIRCRAFT_TYPES_EXCL+=",M700" #

#Twins
$env:AIRCRAFT_TYPES_EXCL+=",PA30" #PIPER PA-30 Twin Comanche
$env:AIRCRAFT_TYPES_EXCL+=",PA44" #PIPER PA-44 Seminole

#Piagio
$env:AIRCRAFT_TYPES_EXCL2+=",P149" #PIAGGIO P-149
$env:AIRCRAFT_TYPES_EXCL2+=",P180" #P180

#Pilatas
$env:AIRCRAFT_TYPES_EXCL+=",PP3" #PILATUS P-3
$env:AIRCRAFT_TYPES_EXCL+=",PP3" #PILATUS P-3
$env:AIRCRAFT_TYPES_EXCL2+=",PC6T" #PILATUS PC-6 Turbo-Porter
$env:AIRCRAFT_TYPES_EXCL+=",PC7" #PILATUS PC-7 Astra
$env:AIRCRAFT_TYPES_EXCL+=",PC9" #PILATUS PC-9 Hudournik
$env:AIRCRAFT_TYPES_EXCL2+=",TEX2" #Beechcraft Raytheon T-6B Texan II based on  Pilatus PC-9
$env:AIRCRAFT_TYPES_EXCL+=",PC12" #PILATUS PC-12
$env:AIRCRAFT_TYPES_EXCL+=",PC12" #Pilatus U-28A Draco
$env:AIRCRAFT_TYPES_EXCL+=",PC21" #PILATUS PC-21
$env:AIRCRAFT_TYPES_EXCL+=",PC24"

#PIPISTREL PIPSTREL
$env:AIRCRAFT_TYPES_EXCL2+=",PIAT" #PIPISTREL Alpha Trainer
$env:AIRCRAFT_TYPES_EXCL2+=",PISI" #PIPSTREL Sinus
$env:AIRCRAFT_TYPES_EXCL2+=",PIVI" #PIPSTREL Virus
$env:AIRCRAFT_TYPES_EXCL2+=",PITA" #PIPSTREL Taurus 503
$env:AIRCRAFT_TYPES_EXCL2+=",PIVE" #PIPSTREL Velis Electro #Electric!!
$env:AIRCRAFT_TYPES_EXCL2+=",PIAE" #PIPISTREL Alpha Electro


#PITTS
$env:AIRCRAFT_TYPES_EXCL2+=",PTS1" #PITTS S-1 Special
$env:AIRCRAFT_TYPES_EXCL2+=",PTS2" #PITTS S-2 Special
$env:AIRCRAFT_TYPES_EXCL2+=",PTSS" #PITTS S-1-11 Super Stinker
$env:AIRCRAFT_TYPES_EXCL2+=",PTMS" #PITTS S-12 Super Stinker


#PZL
$env:AIRCRAFT_TYPES_EXCL2+=",W3" #PZL-SWIDNIK W-3
$env:AIRCRAFT_TYPES_EXCL2+=",M18" #PZL-MIELEC M-18 Dromader
$env:AIRCRAFT_TYPES_EXCL2+=",PZ3T" #PZL-OKECIE PZL-130 Orlik
$env:AIRCRAFT_TYPES_EXCL2+=",PZ04" #PZL-OKECIE PZL-104 Wilga
$env:AIRCRAFT_TYPES_EXCL2+=",PZ4M" #PZL-OKECIE PZL-104M Wilga 2000
$env:AIRCRAFT_TYPES_EXCL2+=",M28" #PZL-MIELEC M-28 Skytruck


#RANS
$env:AIRCRAFT_TYPES_EXCL+=",SAKO" #RANS S-10 Sakota
$env:AIRCRAFT_TYPES_EXCL+=",RS20" #RANS S-20 Raven
$env:AIRCRAFT_TYPES_EXCL+=",RS21" #RANS S-21 Outbound
$env:AIRCRAFT_TYPES_EXCL+=",COY2" #RANS Coyote 2
$env:AIRCRAFT_TYPES_EXCL+=",CRER" #RANS Courier
$env:AIRCRAFT_TYPES_EXCL+=",VTRA" #RANS Venterra

#RAJ 
$env:AIRCRAFT_TYPES_EXCL2+=",XA85" #RAJ HAMSA XA-85
$env:AIRCRAFT_TYPES_EXCL2+=",XAIR" #RAJ HAMSA X-AIR Falcon


#REMOS
$env:AIRCRAFT_TYPES_EXCL+=",GX" #REMOS GX
$env:AIRCRAFT_TYPES_EXCL+=",G3" #REMOS Mirage

#Robin
$env:AIRCRAFT_TYPES_EXCL2+=",R200" #ROBIN Alpha
$env:AIRCRAFT_TYPES_EXCL2+=",HR20" #ROBIN HR-200
$env:AIRCRAFT_TYPES_EXCL2+=",DR40" #ROBIN DR-400
$env:AIRCRAFT_TYPES_EXCL2+=",R100" #ROBIN Aiglon
$env:AIRCRAFT_TYPES_EXCL2+=",R300" #ROBIN R-3000/3100/3120/3140


#SAAB
#Piston
$env:AIRCRAFT_TYPES_EXCL2+=",SB91" #SAAB 91 Safir
#turboprop
$env:AIRCRAFT_TYPES_EXCL2+=",SF34" #SAAB 340
$env:AIRCRAFT_TYPES_EXCL2+=",SB20" #SAAB 2000

#AIRPLANE FACTORY Sling
$env:AIRCRAFT_TYPES_EXCL+=",SLG2" #AIRPLANE FACTORY Sling 2
$env:AIRCRAFT_TYPES_EXCL+=",SLG4" #AIRPLANE FACTORY Sling 4

#STINSON
$env:AIRCRAFT_TYPES_EXCL+=",L5" #STINSON Sentinel
$env:AIRCRAFT_TYPES_EXCL+=",S10" #STINSON 10 Voyager
$env:AIRCRAFT_TYPES_EXCL+=",S108" #STINSON 108 Voyager
$env:AIRCRAFT_TYPES_EXCL2+=",RELI" #STINSON Reliant

#SIAI-MARCHETTI
$env:AIRCRAFT_TYPES_EXCL+=",SM19" #SIAI-MARCHETTI SM-1019
$env:AIRCRAFT_TYPES_EXCL+=",S05R" #SIAI-MARCHETTI S-205-22R

#SOCATA
$env:AIRCRAFT_TYPES_EXCL+=",GY80" #DAHER-SOCATA GY-80 Horizon
$env:AIRCRAFT_TYPES_EXCL+=",TB20" #SOCATA TB-20 Trinidad
$env:AIRCRAFT_TYPES_EXCL+=",TB21" #SOCATA TB-21 Trinidad TC
$env:AIRCRAFT_TYPES_EXCL2+=",TB30" #SOCATA TB-30 Epsilon
$env:AIRCRAFT_TYPES_EXCL+=",TOBA" #SOCATA Tobago
$env:AIRCRAFT_TYPES_EXCL+=",TAMP" #SOCATA TB-9 Tampico
$env:AIRCRAFT_TYPES_EXCL+=",GA7" #DAHER-SOCATA TB-360 Tangara
$env:AIRCRAFT_TYPES_EXCL+=",TBM7" #SOCATA TBM-700A/B/C
$env:AIRCRAFT_TYPES_EXCL+=",TBM8" #SOCATA TBM-850
$env:AIRCRAFT_TYPES_EXCL+=",TBM9" #SOCATA TBM-900/910/930/940
$env:AIRCRAFT_TYPES_EXCL2+=",RALL" #SOCATA Rallye

#SONEX
$env:AIRCRAFT_TYPES_EXCL2+=",SONX" #SONEX AIRCRAFT Sonex
$env:AIRCRAFT_TYPES_EXCL2+=",WAIX" #SONEX Waiex
$env:AIRCRAFT_TYPES_EXCL2+=",XNOS" #SONEX Xenos
$env:AIRCRAFT_TYPES_EXCL2+=",ONEX" #SONEX Onex

#SWEARINGEN
$env:AIRCRAFT_TYPES_EXCL+=",SW3" #SWEARINGEN Merlin 3
$env:AIRCRAFT_TYPES_EXCL+=",SW4" #SWEARINGEN Metro
$env:AIRCRAFT_TYPES_EXCL+=",SX30" #SWEARINGEN SX-300

#SHORT
$env:AIRCRAFT_TYPES_EXCL2+=",SC7" #SHORT Skyvan
$env:AIRCRAFT_TYPES_EXCL2+=",SH33" #SHORT 330 Sherpa
$env:AIRCRAFT_TYPES_EXCL2+=",SH36" #SHORT 360

#TAYLORCRAFT 
$env:AIRCRAFT_TYPES_EXCL+=",TF19" #TAYLORCRAFT F-19 Sportsman
$env:AIRCRAFT_TYPES_EXCL+=",TF21" #TAYLORCRAFT F-21
$env:AIRCRAFT_TYPES_EXCL+=",TAYB" #TAYLORCRAFT BC/BF/BL
$env:AIRCRAFT_TYPES_EXCL+=",TAYD" #TAYLORCRAFT DC/DF/DL
$env:AIRCRAFT_TYPES_EXCL+=",PLUS" #TAYLORCRAFT Plus

#TECNAM /PARTENAVIA
$env:AIRCRAFT_TYPES_EXCL+=",P68" #PARTENAVIA P-68 Observer
$env:AIRCRAFT_TYPES_EXCL2+=",P68T" #PARTENAVIA AP-68 Spartacus
$env:AIRCRAFT_TYPES_EXCL2+=",VTOR" #VULCANAIR Partenavia AP68TP-600 Viator
$env:AIRCRAFT_TYPES_EXCL+=",ASTO" #TECNAM Astore
$env:AIRCRAFT_TYPES_EXCL+=",ECHO" #TECNAM P-92 Echo
$env:AIRCRAFT_TYPES_EXCL+=",SIRA" #TECNAM P-2002 Sierra
$env:AIRCRAFT_TYPES_EXCL+=",BRAV" #TECNAM P-2004 Bravo
$env:AIRCRAFT_TYPES_EXCL+=",P06T" #TECNAM P-2006T
$env:AIRCRAFT_TYPES_EXCL+=",P208" #TECNAM P-2008
$env:AIRCRAFT_TYPES_EXCL+=",P212" #TECNAM P-2012 Traveller
$env:AIRCRAFT_TYPES_EXCL+=",TWEN" #TECNAM Twenty-Ten
$env:AIRCRAFT_TYPES_EXCL+=",OSCR" #PARTENAVIA Oscar Charlie

#THORP 
$env:AIRCRAFT_TYPES_EXCL+=",T18" #THORP Tiger
$env:AIRCRAFT_TYPES_EXCL2+=",T211" #Thorp/INDUS T-211

#TL ULTRALIGHT 
$env:AIRCRAFT_TYPES_EXCL2+=",TL20" #TL ULTRALIGHT TL-2000 Sting
$env:AIRCRAFT_TYPES_EXCL2+=",TL30" #TL ULTRALIGHT TL-3000 Sirius


##Vans
$env:AIRCRAFT_TYPES_EXCL+=",RV1,RV2,RV3,RV4,RV5,RV6,RV7,RV8,RV9,RV10,RV11,RV12,RV13,RV14"

##YAKOVLEV
$env:AIRCRAFT_TYPES_CONFIRMED+=",YK12" #YAKOVLEV Yak-12
$env:AIRCRAFT_TYPES_CONFIRMED+=",YK18" #YAKOVLEV Yak-18U
$env:AIRCRAFT_TYPES_CONFIRMED+=",Y18T" #YAKOVLEV Yak-18T
$env:AIRCRAFT_TYPES_CONFIRMED+=",YK50" #YAKOVLEV Yak-50
$env:AIRCRAFT_TYPES_CONFIRMED+=",YK52" #YAKOVLEV Yak-52
$env:AIRCRAFT_TYPES_CONFIRMED+=",YK55" #YAKOVLEV Yak-55


#ZENAIR\
$env:AIRCRAFT_TYPES_EXCL+=",CH60" #ZENAIR CH-600 Zodiac
$env:AIRCRAFT_TYPES_EXCL+=",CH64" #ZENAIR CH-640 Zodiac
$env:AIRCRAFT_TYPES_EXCL+=",CH65" #ZENAIR CH-650 Zodiac
$env:AIRCRAFT_TYPES_EXCL+=",CH70" #ZENAIR CH-701 Stol
$env:AIRCRAFT_TYPES_EXCL+=",CH75" #ZENAIR CH-750 Cruzer
$env:AIRCRAFT_TYPES_EXCL+=",CH80" #ZENAIR CH-801 Stol
$env:AIRCRAFT_TYPES_EXCL+=",CH2T" #ZENAIR CH-2000 Zenith

#ZLIN
$env:AIRCRAFT_TYPES_EXCL2+=",Z26" #ZLIN Z-26/126/226/326/526/626/726
$env:AIRCRAFT_TYPES_EXCL2+=",Z42" #ZLIN Z-42/142/242

##############Random Single offs#######################

#Pistons
$env:AIRCRAFT_TYPES_EXCL2+=",AVTR" #AERO ADVENTURE Aventura 2
$env:AIRCRAFT_TYPES_EXCL2+=",S450" #AERO-EAST-EUROPE SILA-450
$env:AIRCRAFT_TYPES_EXCL2+=",AE45" #AERO Super Aero 145
$env:AIRCRAFT_TYPES_EXCL2+=",PULS" #Aero Designs Pulsar
$env:AIRCRAFT_TYPES_EXCL2+=",EFOX" #AEROPRO Eurofox
$env:AIRCRAFT_TYPES_EXCL2+=",LGND" #AEROPILOT Legend
$env:AIRCRAFT_TYPES_EXCL2+=",BREZ" #AEROSTYLE Breezer
$env:AIRCRAFT_TYPES_EXCL2+=",F8L" #AEROMERE F-8L Falco
$env:AIRCRAFT_TYPES_EXCL2+=",SVNH" #AEROTEC Savannah
$env:AIRCRAFT_TYPES_EXCL2+=",ERCO" #AIR PRODUCTS F-1 Aircoupe
$env:AIRCRAFT_TYPES_EXCL2+=",ULAC" #AIRCAM
$env:AIRCRAFT_TYPES_EXCL2+=",ALSL" #AIRLONY Skylane
$env:AIRCRAFT_TYPES_EXCL2+=",F260" #AERMACCHI SF-260
$env:AIRCRAFT_TYPES_EXCL2+=",ALIG" #ARION LS-1 Lightning
$env:AIRCRAFT_TYPES_EXCL2+=",ARV1" #ARV Super 2
$env:AIRCRAFT_TYPES_EXCL2+=",VL3" #AVEKO Flamingo
$env:AIRCRAFT_TYPES_EXCL2+=",BEAR" #AVIPRO RB-4 Bearhawk
$env:AIRCRAFT_TYPES_EXCL2+=",NIPR" #AVIONS FAIREY Nipper
$env:AIRCRAFT_TYPES_EXCL2+=",A210" #AQUILA A-210

$env:AIRCRAFT_TYPES_EXCL2+=",FK9" #B&F TECHNIK FK-9
$env:AIRCRAFT_TYPES_EXCL2+=",DUCE" #BAKENG Duce
$env:AIRCRAFT_TYPES_EXCL2+=",PUP" #BEAGLE Pup
$env:AIRCRAFT_TYPES_EXCL2+=",BD4" #BEDE BD-4
$env:AIRCRAFT_TYPES_CONFIRMED+=",ATLA" #BREGUET Atlantic
$env:AIRCRAFT_TYPES_EXCL2+=",FB1A" #BOWERS Fly Baby 1A
$env:AIRCRAFT_TYPES_EXCL2+=",BX2" #BRANDLI Cherry

$env:AIRCRAFT_TYPES_EXCL2+=",GY20" #CAB GY-20 Minicab
$env:AIRCRAFT_TYPES_EXCL2+=",CP10" #CAP AVIATION CAP-10
$env:AIRCRAFT_TYPES_EXCL2+=",CUCA" #CULVER Cadet
$env:AIRCRAFT_TYPES_EXCL2+=",CRUZ" #CSA PS-28 Cruiser
$env:AIRCRAFT_TYPES_EXCL2+=",MCR1" #COLOMBAN Ban-Bi
$env:AIRCRAFT_TYPES_EXCL2+=",CORO" #CORVUS Corone
$env:AIRCRAFT_TYPES_EXCL2+=",CA4" #COM AIR 4
$env:AIRCRAFT_TYPES_EXCL2+=",STST" #CFM Star Streak #ultralight

$env:AIRCRAFT_TYPES_EXCL2+=",DAL4" #DALLACH D-4 Fascination
$env:AIRCRAFT_TYPES_EXCL2+=",D6CR" #DRUINE D-62 Condor
$env:AIRCRAFT_TYPES_EXCL2+=",ALTO" #DIRECT FLY Alto

$env:AIRCRAFT_TYPES_EXCL2+=",EAGX" #EAGLE AIRCRAFT Eagle X-TS
$env:AIRCRAFT_TYPES_EXCL2+=",KR30" #EKOLOT Topaz
$env:AIRCRAFT_TYPES_EXCL2+=",EUPA" #Europa
$env:AIRCRAFT_TYPES_EXCL2+=",JFOX" #EUROALAL Jet Fox # Cool
$env:AIRCRAFT_TYPES_EXCL2+=",LXR" #ELIXIR

$env:AIRCRAFT_TYPES_EXC2L+=",STCH" #FLY SYNTHESIS Storch
$env:AIRCRAFT_TYPES_EXCL2+=",TUCR" #FLYING LEGEND Tucano Replica
$env:AIRCRAFT_TYPES_EXCL2+=",SUBA" #FUJI FA-200 Aero Subaru
$env:AIRCRAFT_TYPES_EXCL2+=",FNKB" #FUNK B
$env:AIRCRAFT_TYPES_EXCL2+=",FBA2" #FOUND FB-2 Bush Hawk

$env:AIRCRAFT_TYPES_EXCL2+=",GB1" #GAME COMPOSITES GameBird
$env:AIRCRAFT_TYPES_EXCL2+=",PINO" #GENERAL AVIA F-22 Pinguino
$env:AIRCRAFT_TYPES_EXCL2+=",GA8" #GIPPSAERO GA-8 Airvan
$env:AIRCRAFT_TYPES_EXCL2+=",GC1" #Globe GC-1 Swift
$env:AIRCRAFT_TYPES_EXCL2+=",SRAI" #GREAT PLAINS Sonerai

$env:AIRCRAFT_TYPES_EXCL2+=",DG15" #HOWARD Nightingale
$env:AIRCRAFT_TYPES_EXCL2+=",HROC" #HARMON Rocket
$env:AIRCRAFT_TYPES_EXCL2+=",COUR" #HELIO Courier

$env:AIRCRAFT_TYPES_EXCL2+=",IR23" #ICA IAR-823
$env:AIRCRAFT_TYPES_EXCL2+=",SKAR" #III Sky Arrow
$env:AIRCRAFT_TYPES_EXCL2+=",C42" #IKARUS C-42 Bison

$env:AIRCRAFT_TYPES_EXCL2+=",ESCP" #Just/REALITY Escapade

$env:AIRCRAFT_TYPES_EXCL2+=",KFAB" #KITPLANES FOR AFRICA Explorer

$env:AIRCRAFT_TYPES_EXCL2+=",M108" #LAMBERT M-108
$env:AIRCRAFT_TYPES_EXCL2+=",ACAM" #LEZA Air Cam
$env:AIRCRAFT_TYPES_EXCL2+=",AC4" #LIGHT WING AC-4
$env:AIRCRAFT_TYPES_EXCL2+=",XL2" #LIBERTY XL-2
$env:AIRCRAFT_TYPES_EXCL2+=",L8" #LUSCOMBE 8




$env:AIRCRAFT_TYPES_CONFIRMED+=",EFUS" #MAGNUS eFusion #hybrid!
$env:AIRCRAFT_TYPES_EXCL2+=",BROU" #MAX HOLSTE Broussard
$env:AIRCRAFT_TYPES_EXCL2+=",MC45" #MEYERS MAC-145
$env:AIRCRAFT_TYPES_EXCL2+=",B209" #MBB BO-209 Monsun
$env:AIRCRAFT_TYPES_EXCL2+=",CP23" #MUDRY CAP-230/1/2
$env:AIRCRAFT_TYPES_EXCL2+=",TOUR" #MILLICER Airtourer
$env:AIRCRAFT_TYPES_EXCL2+=",MX2" #MXR MX-2 Aerobatic
$env:AIRCRAFT_TYPES_EXCL+=",MOR2" #MORRISEY Varga  Nifty

$env:AIRCRAFT_TYPES_EXCL2+=",N3N" #NAVAL AIRCRAFT FACTORY N3N
$env:AIRCRAFT_TYPES_EXCL2+=",NH90" #NHI NH-90

$env:AIRCRAFT_TYPES_EXCL2+=",SYMP" #OMF Symphony
$env:AIRCRAFT_TYPES_EXCL2+=",JB15" #OBERLECHNER JOB-15

$env:AIRCRAFT_TYPES_EXCL2+=",ZZZZ" #Preceptor Stinger 22
$env:AIRCRAFT_TYPES_EXCL2+=",SASY" #PROTECH Sassy
$env:AIRCRAFT_TYPES_EXCL2+=",CT4" #PACIFIC AEROSPACE CT-4 Airtrainer
$env:AIRCRAFT_TYPES_EXCL2+=",TMUS" #PAPA 51 Thunder Mustang
$env:AIRCRAFT_TYPES_EXCL2+=",CP30" #PIEL Emeraude
$env:AIRCRAFT_TYPES_EXCL2+=",CP65" #PORTERFIELD CP-65 Collegiate

$env:AIRCRAFT_TYPES_EXCL2+=",BPAT" #R&B Bearhawk Patrol
$env:AIRCRAFT_TYPES_EXCL2+=",KR2" #RAND KR-2
$env:AIRCRAFT_TYPES_EXCL2+=",CTAH" #RAINBOW SKYREACH Cheetah
$env:AIRCRAFT_TYPES_EXCL2+=",SKYR" #REARWIN Skyranger
$env:AIRCRAFT_TYPES_EXCL2+=",RENE" #Renegade
$env:AIRCRAFT_TYPES_EXCL2+=",RODS" #RIHN One Design
$env:AIRCRAFT_TYPES_EXCL2+=",RLU1" #RLU Super Breezy
$env:AIRCRAFT_TYPES_EXCL2+=",R90R" #RUSCHMEYER R-90-230RG
$env:AIRCRAFT_TYPES_EXCL2+=",D31" #ROLLASON D-31 Turbulent a French single-seat ultralight Homebuilt aircraft
$env:AIRCRAFT_TYPES_EXCL2+=",R185" #Rocket 185

$env:AIRCRAFT_TYPES_EXCL+=",SIDE" #SMYTH Sidewinder
$env:AIRCRAFT_TYPES_EXCL2+=",SF25" #SCHEIBE SF-25 Falke
$env:AIRCRAFT_TYPES_EXCL2+=",AURA" #SUNWARD Aurora S60/70
$env:AIRCRAFT_TYPES_EXCL2+=",SHRK" #SHARK AERO Shark

$env:AIRCRAFT_TYPES_EXCL2+=",KIS4" #TRI-R KIS TR-4
$env:AIRCRAFT_TYPES_EXCL2+=",TR1" #TRIDENT Trigull
$env:AIRCRAFT_TYPES_EXCL2+=",COLT" #TEXAS AIRCRAFT Colt
$env:AIRCRAFT_TYPES_EXCL2+=",L11" #TEMCO Sedan
$env:AIRCRAFT_TYPES_EXCL2+=",TRF1" #TEAM ROCKET F-1
$env:AIRCRAFT_TYPES_EXCL2+=",FOXT" #TEAM TANGO Foxtrot-4
$env:AIRCRAFT_TYPES_EXCL+=",SD4" #TOMARK Viper
$env:AIRCRAFT_TYPES_EXCL2+=",TRDO" #TITAN Tornado SS

$env:AIRCRAFT_TYPES_EXCL2+=",UF10" #URBAN UFM-10 Samba

$env:AIRCRAFT_TYPES_EXCL+=",VR7" #VASHON Ranger R7
$env:AIRCRAFT_TYPES_EXCL+=",L90" #VALMET Redigo
$env:AIRCRAFT_TYPES_EXCL+=",TFUN" #VALENTIN Taifun

$env:AIRCRAFT_TYPES_EXCL+=",WA50" #WASSMER WA-54 Atlantic
$env:AIRCRAFT_TYPES_EXCL2+=",MX1T" #WORLD AIRCRAFT Sentinel
$env:AIRCRAFT_TYPES_EXCL2+=",TAIL" #WITTMAN Tailwind


#Radials
$env:AIRCRAFT_TYPES_EXCL2+=",CJ6" #NANCHANG CJ-6 Yak Trainer Raidal CLlone

#AutoGyro Gyrocopter
$env:AIRCRAFT_TYPES_EXCL2+=",CDUS" #AUTOGYRO Calidus
$env:AIRCRAFT_TYPES_EXCL2+=",CLON" #AUTOGYRO Cavalon
$env:AIRCRAFT_TYPES_EXCL2+=",MT" #Gyrocopter
$env:AIRCRAFT_TYPES_EXCL2+=",MM16" #MAGNI M-16 Tandem Trainer
$env:AIRCRAFT_TYPES_EXCL2+=",MM24" #MAGNI M-24 Orion
$env:AIRCRAFT_TYPES_EXCL2+=",GYRO" #M24 ORION
$env:AIRCRAFT_TYPES_EXCL2+=",SPHA" #AMERICAN AUTOGYRO Spinus



#Cubs
$env:AIRCRAFT_TYPES_EXCL+=",CC11" #CUB CRAFTERS CC-11 Carbon Cub
$env:AIRCRAFT_TYPES_EXCL+=",CC19" #CUB CRAFTERS CC-19 XCub
$env:AIRCRAFT_TYPES_EXCL+=",FOX" #KITFOX
$env:AIRCRAFT_TYPES_EXCL+=",S1" #INTERSTATE S-1 Cadet

#drones
$env:AIRCRAFT_TYPES_CONFIRMED+=",VFHC" #L3 HARRIS HQ-90C
$env:AIRCRAFT_TYPES_CONFIRMED+=",DRON" #MAVIC PRO
$env:AIRCRAFT_TYPES_CONFIRMED+=",Q4" #NORTHROP GRUMMAN RQ-4 Global Hawk
$env:AIRCRAFT_TYPES_CONFIRMED+=",Q9" #GENERAL ATOMICS MQ-9 Reaper
$env:AIRCRAFT_TYPES_CONFIRMED+=",HRON" #IAI Heron Drone

#Sea Planes
$env:AIRCRAFT_TYPES_EXCL2+=",SMAX" #AIRMAX M-22 SeaMax
$env:AIRCRAFT_TYPES_EXCL2+=",LA4" #LAKE LA-4/200 Sea Plane
$env:AIRCRAFT_TYPES_EXCL2+=",LA25" #LAKE LA-250
$env:AIRCRAFT_TYPES_EXCL2+=",A5" #ICON A-5
$env:AIRCRAFT_TYPES_EXCL2+=",PETR" #EDRA Super Petre
$env:AIRCRAFT_TYPES_EXCL2+=",SREY" #PROGRESSIVE AERODYNE SeaRey
$env:AIRCRAFT_TYPES_EXCL2+=",SEAW" #Seawind
$env:AIRCRAFT_TYPES_EXCL2+=",S12" #SPENCER S-12 Air Car
$env:AIRCRAFT_TYPES_EXCL2+=",GDUK" # ELLISON-MAHON Gweduck
$env:AIRCRAFT_TYPES_EXCL2+=",TEAL" #THURSTON Teal


#other Tubobrops
#$env:AIRCRAFT_TYPES_EXCL2+=",EXPR" #Wierd single turoboprop
$env:AIRCRAFT_TYPES_EXCL2+=",AEST" #AEROSTAR 600
$env:AIRCRAFT_TYPES_EXCL2+=",CVLP" #CONVAIR Convairliner
$env:AIRCRAFT_TYPES_EXCL+=",EPIC" #EPIC AIRCRAFT Epic LT
$env:AIRCRAFT_TYPES_EXCL2+=",P750" # PAC P-750 XSTOL
$env:AIRCRAFT_TYPES_EXCL2+=",CRES" #PACIFIC AEROSPACE Cresco
$env:AIRCRAFT_TYPES_EXCL2+=",EXPR" #EXPRESS 2000
$env:AIRCRAFT_TYPES_CONFIRMED+=",S2T" #GRUMMAN S-2 Turbo Tracker


#Other Aerobatic
$env:AIRCRAFT_TYPES_EXCL2+=",G202" #AKROTECH G-202
$env:AIRCRAFT_TYPES_EXCL2+=",ACR2" #ACRO SPORT 2

$env:AIRCRAFT_TYPES_EXCL2+=",E200" #EXTRA EA-200
$env:AIRCRAFT_TYPES_EXCL2+=",E300" #Extra 300
$env:AIRCRAFT_TYPES_EXCL2+=",E400" #EXTRA EA-400
$env:AIRCRAFT_TYPES_EXCL2+=",EXNG" #EXTRA NG

$env:AIRCRAFT_TYPES_EXCL2+=",EDGE" #ZIVKO Edge 540

$env:AIRCRAFT_TYPES_EXCL+=",HUSK" #CHRISTEN Husky
$env:AIRCRAFT_TYPES_EXCL2+=",EAGL" #CHRISTEN Eagle

$env:AIRCRAFT_TYPES_EXCL2+=",ST30" #STAUDACHER S-330 
$env:AIRCRAFT_TYPES_EXCL2+=",TWST" #SILENCE Twister
$env:AIRCRAFT_TYPES_EXCL2+=",LAKR" #LASER Akro Z
$env:AIRCRAFT_TYPES_CONFIRMED+=",SU26" #SUKHOI Su-26 #aerobatic
$env:AIRCRAFT_TYPES_EXCL2+=",XA42" #XTREMAIR XA-42


#BiPlanes
$env:AIRCRAFT_TYPES_CONFIRMED+=",BU31" #BUCKER Bu-131 Jungmann
$env:AIRCRAFT_TYPES_CONFIRMED+=",BU33" #BUCKER Bu-133 Jungmeister

$env:AIRCRAFT_TYPES_CONFIRMED+=",G2T1" #GREAT LAKES 2T-1 Biplne
$env:AIRCRAFT_TYPES_CONFIRMED+=",WICH" #JAVELIN Wichawk
$env:AIRCRAFT_TYPES_CONFIRMED+=",KR34" #KREIDER_REISNER C-4 Challenger
$env:AIRCRAFT_TYPES_CONFIRMED+=",MA5" #MARQUART MA-5 Charger
$env:AIRCRAFT_TYPES_CONFIRMED+=",SNS7" #SORRELL Hiperbipe
$env:AIRCRAFT_TYPES_CONFIRMED+=",BOLT" #STEEN Skybolt #Aerobatic

$env:AIRCRAFT_TYPES_CONFIRMED+=",SA10" #STOLP SA-100 Starduster
$env:AIRCRAFT_TYPES_CONFIRMED+=",SA30" #STOLP Starduster Too

$env:AIRCRAFT_TYPES_EXCL2+=",ST75" #STEARMAN Kaydet
$env:AIRCRAFT_TYPES_EXCL2+=",TVL4" #TRAVEL AIR 4000

$env:AIRCRAFT_TYPES_CONFIRMED+=",WACF" #WACO F Biplane
$env:AIRCRAFT_TYPES_CONFIRMED+=",WACC" #WACO C/S
$env:AIRCRAFT_TYPES_CONFIRMED+=",WACE" #WACO Aristocrat


#Other Big Jets
$env:AIRCRAFT_TYPES_CONFIRMED+=",SU29" #SUKHOI Su-29
$env:AIRCRAFT_TYPES_CONFIRMED+=",SU95" #SUKHOI Superjet 100-95s
$env:AIRCRAFT_TYPES_CONFIRMED+=",P1" #KAWASAKI P-1
$env:AIRCRAFT_TYPES_CONFIRMED+=",KC2" #Kawasaki C-2
$env:AIRCRAFT_TYPES_CONFIRMED+=",IL76" #ILYUSHIN Il-76/82
$env:AIRCRAFT_TYPES_CONFIRMED+=",T204" #TUPOLEV Tu-204/214/224/234

#Electric
$env:AIRCRAFT_TYPES_CONFIRMED+=",JAS4" #JOBY JAS4-1


#Other Small Jets
$env:AIRCRAFT_TYPES_EXCL+=",WW24" #IAI 1124 Westwind
$env:AIRCRAFT_TYPES_EXCL+=",HDJT" #HONDA HondaJet
$env:AIRCRAFT_TYPES_EXCL2+=",S211" #SIAI-MARCHETTI S-211
$env:AIRCRAFT_TYPES_EXCL2+=",AJ27" #COMAC ARJ-21-700 Xiangfeng

#Other fighter Jets
$env:AIRCRAFT_TYPES_CONFIRMED+=",KFIR" #IAI Kfir
$env:AIRCRAFT_TYPES_CONFIRMED+=",FOUG" #AEROSPATIALE CM-170 Magister

#Super cool
$env:AIRCRAFT_TYPES_CONFIRMED+=",X59" #Lockheed Martin X-59 Quesst
$env:AIRCRAFT_TYPES_CONFIRMED+=",F16" #General Dynamics F-16AM Fighting Falcon
$env:AIRCRAFT_TYPES_CONFIRMED+=",WB57" #MARTIN 272

#PRe-WW2
$env:AIRCRAFT_TYPES_CONFIRMED+=",DH82" #DE HAVILLAND DH-82 Tiger Moth
$env:AIRCRAFT_TYPES_CONFIRMED+=",DH87" #DE HAVILLAND DH-87 Hornet Moth
$env:AIRCRAFT_TYPES_CONFIRMED+=",DR1" #FOKKER Dr-1

#WW2 
$env:AIRCRAFT_TYPES_CONFIRMED+=",CAT" #CANADAIR Catalina
$env:AIRCRAFT_TYPES_CONFIRMED+=",CORS" #CHANCE VOUGHT F4U Corsair
$env:AIRCRAFT_TYPES_CONFIRMED+=",SBD" #DOUGLAS SBD Dauntless
$env:AIRCRAFT_TYPES_CONFIRMED+=",P40" #CURTISS P-40 Kittyhawk
$env:AIRCRAFT_TYPES_CONFIRMED+=",MOSQ" #DeHavilland DH98 Mosquito T.II
$env:AIRCRAFT_TYPES_CONFIRMED+=",SWOR" #FAIREY Swordfish
$env:AIRCRAFT_TYPES_CONFIRMED+=",WFOC" #Focke-Wulf 190
$env:AIRCRAFT_TYPES_CONFIRMED+=",TBM" #GRUMMAN G-40 Avenger
$env:AIRCRAFT_TYPES_CONFIRMED+=",BCAT" #GRUMMAN F-8F Bearcat
$env:AIRCRAFT_TYPES_CONFIRMED+=",WCAT" #GRUMMAN F4F Wildcat
$env:AIRCRAFT_TYPES_CONFIRMED+=",HURI" #HAWKER Hurricane
$env:AIRCRAFT_TYPES_CONFIRMED+=",SPIT" #SUPERMARINE Spitfire
$env:AIRCRAFT_TYPES_CONFIRMED+=",SASP" #SUPERMARINE AIRCRAFT Spitfire Mk25/26
$env:AIRCRAFT_TYPES_EXCL2+=",VALI" #CONVAIR Valiant trainer
$env:AIRCRAFT_TYPES_CONFIRMED+=",B25" #NORTH AMERICAN B-25 Mitchell
$env:AIRCRAFT_TYPES_CONFIRMED+=",B26" #DOUGLAS A-26 Invader
$env:AIRCRAFT_TYPES_CONFIRMED+=",B29" #BOEING B-29 Superfortress
$env:AIRCRAFT_TYPES_CONFIRMED+=",P38" #LOCKHEED P-38 Lightning
$env:AIRCRAFT_TYPES_CONFIRMED+=",C46" #CURTISS C-46 Commando
$env:AIRCRAFT_TYPES_CONFIRMED+=",LANC" #AVRO Lancaster
$env:AIRCRAFT_TYPES_CONFIRMED+=",P63" #BELL P-63 Kingcobra
$env:AIRCRAFT_TYPES_CONFIRMED+=",ME08" #MESSERSCHMITT Bf-108 Taifun


###################Helos###################################################
#Bell
#Piston
$env:AIRCRAFT_TYPES_EXCL+=",B47G" #BELL 47G
$env:AIRCRAFT_TYPES_EXCL+=",B47T" #SOLOY Bell 47
$env:AIRCRAFT_TYPES_EXCL+=",B47J" #BELL 47J
#turoboprop
$env:AIRCRAFT_TYPES_EXCL+=",B06" #BELL 206 JetRanger
$env:AIRCRAFT_TYPES_EXCL+=",B212" #BELL 212
$env:AIRCRAFT_TYPES_EXCL+=",B214" #BELL 214
$env:AIRCRAFT_TYPES_EXCL+=",B230" #BELL 230
$env:AIRCRAFT_TYPES_EXCL+=",B407" #BELL 407
$env:AIRCRAFT_TYPES_EXCL+=",B412" #BELL 412
$env:AIRCRAFT_TYPES_EXCL+=",B427" #BELL 427
$env:AIRCRAFT_TYPES_EXCL+=",B429" #BELL 429 GlobalRanger
$env:AIRCRAFT_TYPES_EXCL+=",B430" #BELL 430
$env:AIRCRAFT_TYPES_EXCL+=",B505" #BELL 505 JetRanger X
$env:AIRCRAFT_TYPES_EXCL+=",UH1" #BELL UH-1 Huey
$env:AIRCRAFT_TYPES_CONFIRMED+=",HUCO" #BELL AH-1 HueyCobra
#Tilt
$env:AIRCRAFT_TYPES_CONFIRMED+=",B609" #Tiltrotor

#Eurocopter
$env:AIRCRAFT_TYPES_EXCL+=",EC25" #AIRBUS HELICOPTERS EC-225/725
$env:AIRCRAFT_TYPES_EXCL+=",EC30" #AIRBUS HELICOPTERS EC-130
$env:AIRCRAFT_TYPES_EXCL+=",EC35" #AIRBUS HELICOPTERS EC-135/635
$env:AIRCRAFT_TYPES_EXCL+=",EC45" #Airbus Helicopters UH-72A Lakota
$env:AIRCRAFT_TYPES_EXCL+=",EC55" #AIRBUS HELICOPTERS EC-155
$env:AIRCRAFT_TYPES_EXCL+=",EC20" #AIRBUS HELICOPTERS EC-120
$env:AIRCRAFT_TYPES_EXCL+=",H160" #AIRBUS HELICOPTERS H-160
$env:AIRCRAFT_TYPES_EXCL+=",EC75" #AIRBUS HELICOPTERS EC-175
$env:AIRCRAFT_TYPES_CONFIRMED+=",TIGR" #AIRBUS HELICOPTERS EC-665 Tiger

#Euocopter
$env:AIRCRAFT_TYPES_EXCL+=",BK17" #EUROCOPTER BK117 C-1/2
$env:AIRCRAFT_TYPES_EXCL+=",B105" #EUROCOPTER BO-105
$env:AIRCRAFT_TYPES_EXCL2+=",AS3B" #Eurocopter AS332M1 Super Puma

#Robinson
$env:AIRCRAFT_TYPES_EXCL+=",R22,R44,R66"

#AEROSPATIALE
$env:AIRCRAFT_TYPES_EXCL2+=",PUMA" #AEROSPATIALE SA-330 Puma
$env:AIRCRAFT_TYPES_EXCL2+=",AS32" #AEROSPATIALE AS-332 Super Puma
$env:AIRCRAFT_TYPES_EXCL+=",AS55" #AEROSPATIALE AS-355 Ecureuil 2
$env:AIRCRAFT_TYPES_EXCL+=",AS50" #AEROSPATIALE AS-350 Ecureuil
$env:AIRCRAFT_TYPES_EXCL2+=",AS65" #Coast Guard Helo

#HUGHES
$env:AIRCRAFT_TYPES_EXCL+=",H269" #HUGHES Sky Knight
$env:AIRCRAFT_TYPES_EXCL+=",H500" #HUGHES 500
$env:AIRCRAFT_TYPES_EXCL+=",H900" #HUGHES 900

#AgustaWestland Leonardo
#$env:AIRCRAFT_TYPES_EXCL+=",G2CA"
$env:AIRCRAFT_TYPES_EXCL2+=",A109" #AGUSTA AW-109 Grand
$env:AIRCRAFT_TYPES_EXCL2+=",A119" #AgustaWestland TH-73A Thrasher
$env:AIRCRAFT_TYPES_EXCL2+=",A119" #Leonardo TH-73A Trasher
$env:AIRCRAFT_TYPES_EXCL2+=",A139" #AGUSTA AW-139
$env:AIRCRAFT_TYPES_EXCL2+=",A169" #AGUSTA AW-169
$env:AIRCRAFT_TYPES_EXCL2+=",A189" #AGUSTA AW-189
$env:AIRCRAFT_TYPES_EXCL2+=",EH10" #AGUSTA WESTLAND EH-101 Merlin
$env:AIRCRAFT_TYPES_EXCL2+=",LYNX" #AGUSTAWESTLAND AW-159 Super Lynx

#SIKORSKY
$env:AIRCRAFT_TYPES_EXCL+=",S52" #SIKORSKY S-52
$env:AIRCRAFT_TYPES_EXCL+=",S58T" #SIKORSKY S-58T
$env:AIRCRAFT_TYPES_EXCL2+=",S61" #Sikorsky VH-3D Sea King
$env:AIRCRAFT_TYPES_CONFIRMED+=",S64" #SIKORSKY S-64 Skycrane
$env:AIRCRAFT_TYPES_EXCL+=",S76" #SIKORSKY S-76 Spirit
$env:AIRCRAFT_TYPES_EXCL+=",S92" #SIKORSKY S-92 Helibus




#Military Helos
$env:AIRCRAFT_TYPES_EXCL2+=",H46" #BOEING-VERTOL CH-46 Sea Knight
$env:AIRCRAFT_TYPES_CONFIRMED+=",H47" #BOEING-VERTOL CH-47 Chinook
$env:AIRCRAFT_TYPES_EXCL2+=",H53" #SIKORSKY CH-53
$env:AIRCRAFT_TYPES_EXCL2+=",H53S" #Sikorsky CH-53E Super Stallion
$env:AIRCRAFT_TYPES_EXCL2+=",H60" #Sikorsky MH-60T Jayhawk
$env:AIRCRAFT_TYPES_EXCL2+=",H60" #SIKORSKY UH-60 Black Hawk
$env:AIRCRAFT_TYPES_EXCL2+=",H60" #Sikorsky HH-60W Jolly Green II
$env:AIRCRAFT_TYPES_EXCL2+=",S61R" #SIKORSKY S-61R
$env:AIRCRAFT_TYPES_CONFIRMED+=",H64" #MCDONNELL DOUGLAS AH-64 Apache
$env:AIRCRAFT_TYPES_CONFIRMED+=",H64" #Boeing AH-64E Apache


#Other
$env:AIRCRAFT_TYPES_EXCL+=",ELTO" #CONTINENTAL COPTER El Tomcat
$env:AIRCRAFT_TYPES_EXCL+=",EXPL" #MCDONNELL-DOUGLAS MD-900 Explorer
$env:AIRCRAFT_TYPES_EXCL+=",MD52" #
$env:AIRCRAFT_TYPES_EXCL+=",MD60" #MD Helicopters MD 600
$env:AIRCRAFT_TYPES_EXCL+=",GAZL" #AEROSPATIALE SA-341 Gazelle
$env:AIRCRAFT_TYPES_EXCL+=",UHEL" #CH77 Ranabot
$env:AIRCRAFT_TYPES_EXCL+=",EN28" #ENSTROM F-28
$env:AIRCRAFT_TYPES_EXCL+=",EN48" #ENSTROM TH-28
$env:AIRCRAFT_TYPES_CONFIRMED+=",MI8" #MIL Mi-8/9/17/19/171/172
$env:AIRCRAFT_TYPES_CONFIRMED+=",KMAX" #KAMAN K-Max
$env:AIRCRAFT_TYPES_EXCL2+=",SURN" #KOREA AEROSPACE Surion
$env:AIRCRAFT_TYPES_EXCL+=",G2CA" #GUIMBAL G-2 Cabri
$env:AIRCRAFT_TYPES_EXCL+=",CH7" #HELI-SPORT CH-7 Kompress
$env:AIRCRAFT_TYPES_EXCL+=",EXEC" #ROTORWAY Exec



##############################################
###Non aircraft
$env:AIRCRAFT_TYPES_CONFIRMED+=",SHIP" #PATHFINDER 1 #Airship
$env:AIRCRAFT_TYPES_CONFIRMED+=",BALL" #Lockheed Martin Thethered Aerostat
$env:AIRCRAFT_TYPES_CONFIRMED+=",TWR" #Control TOwer

#Truely Unknowon
$env:AIRCRAFT_TYPES_CONFIRMED+=",SERV" #
$env:AIRCRAFT_TYPES_CONFIRMED+=",GND" #