name: 'Release'
permissions:
  contents: write
  packages: write
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        shell: bash
        run: |
          go test ./internal/... --count 1

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-22.04
    outputs:
      new_release_version: ${{ steps.check_semantic.outputs.new_release_version }}
      new_release_notes: ${{ steps.check_semantic.outputs.new_release_notes }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          go build -o jetspotter -ldflags "-linkmode external -extldflags -static" cmd/jetspotter/jetspotter.go

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: jetspotter
          path: jetspotter

      - name: Install conventional-changelog-conventionalcommits
        run: npm install conventional-changelog-conventionalcommits

      - name: Check semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: check_semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    needs: [build]
    if: needs.build.outputs.new_release_version
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: jetspotter

      - name: Create the release
        uses: ncipollo/release-action@v1
        id: release
        with:
          artifacts: jetspotter
          name: ${{ needs.build.outputs.new_release_version }}
          body: ${{ needs.build.outputs.new_release_notes }}
          tag: ${{ needs.build.outputs.new_release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  image:
    name: Push container image
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REGISTRY: ghcr.io
    if: needs.build.outputs.new_release_version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ github.repository }}"
          docker build -t ${IMAGE}:${{ needs.build.outputs.new_release_version }} -t ${IMAGE}:latest .
          docker push ${IMAGE}:${{ needs.build.outputs.new_release_version }}
          docker push ${IMAGE}:latest

  notification:
    name: Send notification on failure
    needs: [build, release, image]
    runs-on: ubuntu-latest
    steps:
      - name: Send alert to slack
        id: slack
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C05URKA9NNB'
          slack-message: 'Failed build: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_GOOSE }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
