name: 'Release'
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        shell: bash
        run: |
          go test ./internal/... --count 1

  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-22.04
    outputs:
      new_release_version: ${{ steps.check_semantic.outputs.new_release_version }}
      new_release_notes: ${{ steps.check_semantic.outputs.new_release_notes }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3

      - name: Build
        id: build
        run: |
          go build -o jetspotter -ldflags "-linkmode external -extldflags -static" cmd/jetspotter/jetspotter.go

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: jetspotter
          path: jetspotter

      - name: Install conventional-changelog-conventionalcommits
        run: npm install conventional-changelog-conventionalcommits

      - name: Check semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: check_semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    needs: [build]
    if: needs.build.outputs.new_release_version
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: jetspotter

      - name: Create the release
        uses: ncipollo/release-action@v1
        id: release
        with:
          artifacts: jetspotter
          name: ${{needs.build.outputs.new_release_version }}
          body: ${{ needs.build.outputs.new_release_notes }}
          tag: ${{ needs.build.outputs.new_release_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
