name: 'Tests'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        shell: bash
        run: |
          go test ./internal/... --count 1
